### ISSUE TITLE
UXP: Failed to load the devtools plugin.

### ISSUE THREAD

**Issue by xblt** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#1]
![image](https://user-images.githubusercontent.com/112146913/208876299-be1fb006-eb78-4ddf-87f1-c81dbebe65eb.png)
![image](https://user-images.githubusercontent.com/112146913/208876432-643094b5-b0db-45d5-a8e5-1316f9eccebe.png)

Could this be a conflict regarding the having a genuine photoshop version? asking for a friend

**Comment by AbdullahAlfaraj** [comment]
hi @xblt,
maybe you need to change "minVersion": "24.0.0" in manifest.json
change it to the same version as yours or even lower
something like "23.0.0"

**Comment by AbdullahAlfaraj** [comment]
@xblt also don't forget remove the plugin and add it again. you need to add the manifest.json again after every change.

**Comment by coreyb42** [comment]
Might be good to change it repo-side to whatever the min version "really" is. I have a genuine copy and just got bit by this, myself. I'm sure some people might be at that version for various reasons, and if it works, might as well allow it to install.
