### ISSUE TITLE
Port number is hardcoded as 7860 in multiple places in the code

### ISSUE THREAD

**Issue by bouchert** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#10]
Some installs of Automatic1111 need different port ranges.  There should be some configurable way of setting the port if it is not the default.

**Comment by XenonofArcticus** [comment]
This would be a fairly easy issue to contribute a pull request fix for.

**Comment by micmicmicmicmicchan** [comment]
Same issue here, my a1111 is using port:7861 but the plugin is connecting to 7860...

**Comment by micmicmicmicmicchan** [comment]
> Same issue here, my a1111 is using port:7861 but the plugin is connecting to 7860...

i just figured out that i can just add --port 7860 after the argument.

**Comment by screan** [comment]
> 

what did you end up changing? the webui-user.bat? i use port 7861 too

**Comment by micmicmicmicmicchan** [comment]
> @micmicmicmicmicchan
> 
> what did you end up changing? the webui-user.bat? i use port 7861 too

yes, just add [--port 7860] after [set COMMANDLINE_ARGS=] of [webui-user.bat]
But, if some program is using the port 7860, it will come back with an error

**Comment by AbdullahAlfaraj** [comment]
I've jsut merge #8 ,
pull and then edit the "start_server.bat"
```
set SD_URL=http://127.0.0.1:7860
```
set it to your remote auto1111 address, or just change the port if that is all you need.
that should fix your

**Comment by screan** [comment]
hmm still cannot connect. 

my mac connects to my PC running SD using http://192.XXX.XX.XX:7861

**Comment by AbdullahAlfaraj** [comment]
@screan you can copy and paste your automatic1111 url into SD URL field in the setting tab. 
If that doesn't solve it, you should open an new issue.
