### ISSUE TITLE
Question: Why it can't be used on lower versions of Photoshop

### ISSUE THREAD

**Issue by Who-is-dk** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#109]
Is it because of uxp or some special support in new version?

**Comment by AbdullahAlfaraj** [comment]
@Who-is-dk You are correct - UXP is relatively new and constantly improving.

Bugs and issues get fixed every release, and new features are constantly added and improved upon.
Here's one example of a UXP feature that has not officially been released, but that will require an increased version requirement when it does:

https://developer.adobe.com/photoshop/uxp/2022/ps_reference/media/imaging/
