### ISSUE TITLE
what software is this?

### ISSUE THREAD

**Issue by kazzantip39** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#117]
Hi, can help me with this problem pls
the second step is unclear. what is this window from which program?
https://user-images.githubusercontent.com/7842232/217214062-4c2fef9e-8d49-46a0-aa3b-80c4975f8a70.gif

**Comment by AbdullahAlfaraj** [comment]
This is Automatic1111, I show you how to install it in this video:
https://www.youtube.com/watch?v=BNzdhEpFHrg&ab_channel=Abdsart
