### ISSUE TITLE
Creative Cloud Error

### ISSUE THREAD

**Issue by tushoujiegaobao** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#118]
![QQ截图20230225220027](https://user-images.githubusercontent.com/125947603/221361007-a11d2bd1-bf5c-4031-9ac4-42d8e095593a.png)
what's going on and how to solve it

**Comment by AbdullahAlfaraj** [comment]
@tushoujiegaobao When is the error coming up? Is it when you run a .ccx file?
You will need Photoshop V24 or later. Do you have that?

**Comment by tushoujiegaobao** [comment]
> @tushoujiegaobao错误什么时候出现？是运行. ccx文件的时候吗？您需要Photoshop V24或更高版本。你有那个吗？
I don't have the version of Photoshop V24. I ran the. ccx file yesterday and then this window popped up. Would you please give me a new ps version? Thank you

**Comment by tushoujiegaobao** [comment]
> @tushoujiegaobao错误什么时候出现？是运行. ccx文件的时候吗？您需要Photoshop V24或更高版本。你有那个吗？

Sorry, my PS version is v23. I'll update it
