### ISSUE TITLE
CCX file not working

### ISSUE THREAD

**Issue by Joeyd348039** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#119]
I have Photoshop V24.2 . Keeps on saying it's not a supported document.

**Comment by AbdullahAlfaraj** [comment]
where do you get this error message? can you provide a screenshot?

**Comment by Joeyd348039** [comment]
Inside of photoshop. I get the error when I drag it into photoshop or try "Open As". 
![photoshoperror](https://user-images.githubusercontent.com/3986248/221428186-71578351-1c25-4983-ba21-4a3df0df9f0a.jpg)

**Comment by AbdullahAlfaraj** [comment]
you can't install the plugin by dragging the .ccx file into photoshop. 
what happen when you double click the .ccx file?

**Comment by AbdullahAlfaraj** [comment]
@Joeyd348039 Download creative cloud 5.7 or above.  mine is 5.10
Then you should be able to open .ccx file by double clicking.
![image](https://user-images.githubusercontent.com/7842232/221741447-00c80efd-f05a-4abc-a11f-eec5a820aae7.png)

**Comment by vincentline** [comment]
Prompt no compatible software found

**Comment by AbdullahAlfaraj** [comment]
@vincentline what creative cloud version do you have?
you have 5.7 or higher, and it still will not open your .ccx files.
try to install UXP from the creative cloud app.

**Comment by Xenocephal** [comment]
Is there any way install it without creative cloud?

**Comment by lyonnel4** [comment]
> Is there any way to install it without creative cloud?

just put the unzipped folder in your photoshop Plugins folder.

**Comment by RoyalGoose** [comment]
![image](https://user-images.githubusercontent.com/58046193/223110038-1ad5df1a-15e7-40cf-99b6-5433245fff02.png)


> > Is there any way to install it without creative cloud?
> 
> just put the unzipped folder in your photoshop Plugins folder.
same error,
it still no working

**Comment by AbdullahAlfaraj** [comment]
@RoyalGoose you're doing the manual installation correctly, but you have version v23.0.
you need photoshop version 24.0 or higher.

**Comment by RoyalGoose** [comment]
@AbdullahAlfaraj thank you!

**Comment by Xenocephal** [comment]
@AbdullahAlfaraj Thank you for your advice, it works correctly for me.

**Comment by aztack** [comment]
> > Is there any way to install it without creative cloud?
> 
> just put the unzipped folder in your photoshop Plugins folder.

Where is the 'plugins folder' on Mac?
