### ISSUE TITLE
Txt2img Highres Fix not working on 1.1.7

### ISSUE THREAD

**Issue by LiJT** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#123]
![1](https://user-images.githubusercontent.com/11270197/222628574-96be9454-0641-4fd1-927e-9f69bb86aeaf.png)

Upper image from PS, bottom image from webui.

Please check the screenshot above, On the right i put the exact same parameter, the result has much higher resolution. I dont think the current version Txt2img highres fix is working as intended at the moment. Hopefully next version get patched! Thank you so much for your hardwork Abdullah!

**Comment by AbdullahAlfaraj** [comment]
@LiJT, thank you for your kind words.
There is a bug in 1.1.7 where the high resolution fix will not work for the resolution 512x512 -
but it will still work for larger images.

We will get this patched in our next version.

**Comment by LiJT** [comment]
> @LiJT, thank you for your kind words. There is a bug in 1.1.7 where the high resolution fix will not work for the resolution 512x512 - but it will still work for larger images.
> 
> We will get this patched in our next version.

Thank you! I m trying your latest 1.2 now!

**Comment by AbdullahAlfaraj** [comment]
@LiJT thank you, and let me know if you still experience the same issue in the newer version
