### ISSUE TITLE
Inpainting: Extremely slow plugin command execution v1.2.0

### ISSUE THREAD

**Issue by studioSnowfort** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#125]
Plugin command gets unusably slow when it gets to the mask group creation step. Takes a few minutes on a small 1024x0124 one layer image, and when working on a very large file it completely freezes Photoshop. Inpainting works fine on the same large file using v1.1.7.

**Comment by Alchete** [comment]
Noticed the same.  Just converting the mask freezes the entire UI and halts the plugin progress bar at about 1/4.

**Comment by AbdullahAlfaraj** [comment]
This has been solved in v1.2.2.ccx
go to the settings menu and select Slow PC for the optimization option.

![image](https://user-images.githubusercontent.com/7842232/225092498-22fe8dc0-651a-4d84-84b4-28a0392dee3b.png)
