### ISSUE TITLE
Preview images not loading when using ControlNet

### ISSUE THREAD

**Issue by jwooldridge234** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#127]
Not sure if I'm doing something wrong or this feature isn't in there yet- running v1.20 and image previews work great on every other mode but don't show up at all when I'm using Controlnet- I just see the image when it's finished. I'm on MacOS M1 running Venture 13.0.1 and Photoshop v24.2.

**Comment by AbdullahAlfaraj** [comment]
You're not doing anything wrong, but the ControlNet API is experimental. One of its quirks is that it pauses any communication to automatic1111 until the current request is finished.
Hopefully the developer working on the ControlNet API will resolve this issue.

**Comment by jwooldridge234** [comment]
Gotcha, thanks! Thought it might be something like that.

**Comment by AbdullahAlfaraj** [comment]
We've already fixed this issue for those using the UXP version of the plugin. However, we will release a patch for those using the ccx version very soon.

**Comment by jwooldridge234** [comment]
Awesome, thanks so much!

**Comment by AbdullahAlfaraj** [comment]
This has been fixed in v1.2.2.ccx
you will need to update your Auto1111 and ControlNet extension too.

**Comment by VisionaryMind** [comment]
@jwooldridge234 Have you gotten ControlNet to work in this plugin? As I state in [#156](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/156), the interface displays the models without an issue, but the plugin doesn't use ControlNet at all to modify the main image. Perhaps there are some special steps that need to be taken to get this to work (other than clicking Enable). Hopefully, you may have an idea.

**Comment by AbdullahAlfaraj** [comment]
read the following to get it working: 
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/172
