### ISSUE TITLE
Unable to load the plug-in correctly

### ISSUE THREAD

**Issue by salier** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#128]
![image](https://user-images.githubusercontent.com/28691601/223061094-b7a8faf7-4632-48b9-9829-561fa49b23b1.png)
![image](https://user-images.githubusercontent.com/28691601/223061206-e24f3f5b-03fe-481d-b56b-17a5f63e7284.png)
![image](https://user-images.githubusercontent.com/28691601/223062621-c0b287e9-ffa8-4311-937a-10e320fccd95.png)

As shown in the figure, it doesn't seem to work properly

**Comment by XXXKAY** [comment]
me too

**Comment by AbdullahAlfaraj** [comment]
I recommend you follow the instruction in the one click installation section.
And only use the uxp installation method if you are a developer and want to modify the code.

Also, you will need Photoshop v24.0 or higher.

**Comment by AbdullahAlfaraj** [comment]
@annasophiachristianahahn it's a one-click installer. no other installations or modifications are necessary as long as you can run ccx file. 
Read the following issue if you are unable to run the .ccx file https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/119

**Comment by annasophiachristianahahn** [comment]
When I click the ccx file with the latest version of photoshop + cc installed nothing happens- where can I find the zip for manual installation? When I put the ccx file manually in the plugins folder nothing happensOn Mar 7, 2023, at 11:47 AM, Abdullah Alfaraj ***@***.***> wrote:﻿
@annasophiachristianahahn it's a one-click installer. no other installations or modifications are necessary as long as you can run ccx file.
Read the following issue if you are unable to run the .ccx file #119

**Comment by AbdullahAlfaraj** [comment]
@annasophiachristianahahn I've updated the readme page for instruction on how to install using the Unzip method:

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#method-2-the-unzip-method
