### ISSUE TITLE
Can not choose controlnet model

### ISSUE THREAD

**Issue by RoyDingZF** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#132]
the second dropdown menu for selecting model is empty. I suppose there should be models to choose from like in WebUI. Is it because I didn't use official versions of controlnet models?

**Comment by AbdullahAlfaraj** [comment]
Some of the menus in this plugin are dynamic.
What that means is that they need to be populated with data from Automatic1111.
If you run the plugin or start it before you run Automatic1111,
you will end up with empty menus.
To fix this, use the refresh buttons within the plugin.
This will repopulate the menus automatically.

**Comment by MisterMike** [comment]
Had the same issue, needed to install controlnet extension in Auto1111 (via web gui) and put the appropriate controlnet model in the right place.

**Comment by MadM4tt** [comment]
doesn't work for me so far... 
i put the models in:
\stable-diffusion-webui-master\extensions\sd-webui-controlnet\models
and in:
\stable-diffusion-webui-master\extensions\ControlNet\models
still the filter / model selection in PS remains emtpy.
Any hints?

btw Thank you for the great for Abdullah!

**Comment by MadM4tt** [comment]
just found out i first need to use the controlnet models within the webUI so it downloads whatever needs to be downloaded first. Then they also appear in PS-plugin.
