### ISSUE TITLE
COMMANDLINE_ARGS does not contain --api, API won't be mounted.

### ISSUE THREAD

**Issue by WesKro** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#134]
I am having a hard time getting past this and when I try to use the plug in I get a message that the --api is not there but it is. I am open to any suggestions.

**Comment by WesKro** [comment]
![Screenshot 2023-03-06 at 1 25 08 PM](https://user-images.githubusercontent.com/127151072/223234402-3b8edac7-a363-4a13-86b2-fc2b7ef47c78.png)

**Comment by WesKro** [comment]
![Screenshot 2023-03-06 at 1 25 59 PM](https://user-images.githubusercontent.com/127151072/223234485-b23bf6d2-9073-4171-987d-7a8e4d3e54e8.png)

**Comment by WesKro** [comment]
![Screenshot 2023-03-06 at 1 26 33 PM](https://user-images.githubusercontent.com/127151072/223234565-b354e874-a0aa-4f05-b672-3761c428c348.png)

**Comment by AbdullahAlfaraj** [comment]
This is related to Automatic1111. It could be that you are using an older version of the software.

**Comment by EliasMunk** [comment]
I'm having the same issue.

**Comment by AbdullahAlfaraj** [comment]
@EliasMunk I need more information to be able to help, more specifically link me to the instructions you followed to install Automatic1111

**Comment by EliasMunk** [comment]
I followed this Apple Sillicon install 1to1Installation on Apple Silicongithub.comMed bedste hilsner, Elias Munk————————————————Danish actor & screenwriter Proudly represented by:LisaRichards agency, UKPCM Intl, USA+45 52 39 78 80www.eliasmunk.dkOn 8 Mar 2023, at 16.19, Abdullah Alfaraj ***@***.***> wrote:﻿
@EliasMunk I need more information to be able to help, more specifically link me to the instructions you followed to install Automatic1111

**Comment by AbdullahAlfaraj** [comment]
@WesKro @EliasMunk .bat file will not work for you since both of you are running on MacOS
you need to add the --api flags to same file that you use to run "auto1111 webui"
It could be this: 
![image](https://user-images.githubusercontent.com/7842232/223771553-aeaca238-3c62-402f-977f-49485546569e.png)

**Comment by EliasMunk** [comment]
> 

You fixed it. Thank you so much!!!! Actually it wasn't in webui-macos-env.sh, but that file guided me to webui-user.sh, which had the option to add --api to commandline_args
