### ISSUE TITLE
New ControlNet preprocessors do not appear

### ISSUE THREAD

**Issue by cpiscos** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#135]
ControlNet added some new preprocessors like "binary" that are not visible in the PS plugin even though it shows in the webui.

**Comment by AbdullahAlfaraj** [comment]
@cpiscos thanks for pointing that out - the preprocesses list seems to be hardcoded in the ControlNet extension without an easy way to access it. I'll add a way to fix that in on upcoming patch.

**Comment by hjdskhooba** [comment]
Hi, 
I am new to open source
Can I try to resolve this ?

**Comment by AbdullahAlfaraj** [comment]
@cpiscos This issue has been fixed as of version v1.2.2
@hjdskhooba my apologies - I didn't see your message. Had I, I would have replied much earlier.

**Comment by hjdskhooba** [comment]
@AbdullahAlfaraj No problem, I'll try to work with other issue
