### ISSUE TITLE
Compatible app required when open file .ccx to creative cloud desktop

### ISSUE THREAD

**Issue by bunnyreals** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#140]
Just like the title, when I following to this tut : https://user-images.githubusercontent.com/7842232/217213943-3e2a588d-3ed8-4757-ba69-9846b55a1b36.gif
I have a problem when opening file .ccx into creative cloud desktop and it said like the image below:
![image](https://user-images.githubusercontent.com/127244587/223524439-6a6fd815-0f8c-44fd-9496-e2a70dbf1688.png)
Here is my adobe creative version:
![image](https://user-images.githubusercontent.com/127244587/223525085-c6c99f44-0597-4bda-a4cd-32091a4e29c1.png)

**Comment by AbdullahAlfaraj** [comment]
@bunnyreals did you solve this error by installing photoshop?
