### ISSUE TITLE
automatic1111 is offline

### ISSUE THREAD

**Issue by agezy** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#147]
how do I fix this

**Comment by AbdullahAlfaraj** [comment]
I need more Information,
what OS do you have? 
Do you have automatic1111 webui installed?
You need to have the webui running in the background.

**Comment by FSint653** [comment]
@AbdullahAlfaraj in my case its macos macos ventura 13.2

**Comment by AbdullahAlfaraj** [comment]
@FSint653 you will need to install Automatic1111 on macOS and run it.

**Comment by FSint653** [comment]
Just installed and webui is active, but now there is another error on plugging since its irrelevant to this question, I am starting a new one
