### ISSUE TITLE
Python version check in start_server.sh fails for 3.10

### ISSUE THREAD

**Issue by ArtemKo7v** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#148]
I suppose this is not correct:
```
~/automatic/extensions/Auto-Photoshop-StableDiffusion-Plugin$ ./start_server.sh
Already up to date.
Your version (Python 3.10.6) not valid, should be >3.7
```

**Comment by AbdullahAlfaraj** [comment]
@ArtemKo7v What OS are you running?
@evvfebruary Can you take a look at this issue

**Comment by evvfebruary** [comment]
@AbdullahAlfaraj 
Yep, of course, checking it right now!

**Comment by evvfebruary** [comment]
@ArtemKo7v 
Thank's for spotlight this issue!

Fixed this in https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/pull/152

**Comment by ArtemKo7v** [comment]
Works now. Thank you!
