### ISSUE TITLE
Feature request - Metadata saved inside smart object layer. Model, Seed, steps, cfg and sampler.

### ISSUE THREAD

**Issue by Kafkanistan** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#15]
As every new generated image/layer is created as a smart object inside photoshop it is possible to save metadata for it individually.
Double clicking a smart object opens it as a PSB file in Photoshop, this makes it possible to put metadata in it that you can access by pressing Command+Option+Shift+I (Mac) or Ctrl+Alt+Shift+I (Windows) or in the menu File--> File Info. When you close the layer it will ask you to save it and it will be embedded inside the master photoshop file.

One could probably make function/macro that could extract this info from a layer and populate the plug-in with it's settings.
It would also be very good if the plug-in could have a selectable History tab/list for previously generated metadata in case you want to replicate what you have done.
What it could save would at bare minimum be: Model, Seed, steps, cfg and sampler. Perhaps even Mask blur and size?

**Comment by AbdullahAlfaraj** [comment]
@Kafkanistan this is an excellent suggestion, I will be working on it.

**Comment by AbdullahAlfaraj** [comment]
@Kafkanistan thank you again for the suggestion, you can now find all of your generated images in the history tab.
from there, you can reuse your previous settings/metadata and populate the plugin ui with it.
