### ISSUE TITLE
You need to select valid ControlNet model

### ISSUE THREAD

**Issue by SmoothlyMeaning** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#150]
Hi, for some reason in the tab with controllnet scripts do not open, I do not know why, I googled and could not find the error, I installed controllnet, but it still does not work
<img width="256" alt="image" src="https://user-images.githubusercontent.com/33717204/224141135-1b2af5d0-459d-4fcf-b1b1-a2708ff6b2d7.png">
<img width="419" alt="image" src="https://user-images.githubusercontent.com/33717204/224141198-aa54b486-91ff-4e2f-8f3c-3aa0ee632bd0.png">

**Comment by SmoothlyMeaning** [comment]
oh, sorry, i'm such a fool) just needed to load the models for the controllnet.

**Comment by AbdullahAlfaraj** [comment]
No worries - if you run the plugin before you start Auto1111, you might see a missing menu.
All you need to do is click the 'Refresh' button, once you're sure Auto1111 is running. That will fix the issue and repopulate all the missing menus.
