### ISSUE TITLE
mask image is not available ControlNet

### ISSUE THREAD

**Issue by suprasteen** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#151]
the following message "mask image is not available" appears when you press the "View Mask" button. what am I doing wrong?

**Comment by suprasteen** [comment]
![image](https://user-images.githubusercontent.com/58467918/224183562-6cbc949c-ebf4-4cd3-81cb-24fd075581d8.png)

**Comment by SmoothlyMeaning** [comment]
same here

**Comment by ryanhsu2021** [comment]
same here

**Comment by SmoothlyMeaning** [comment]
i thinki got it. you must first generate some image with controlnet model, then mask popup

**Comment by AbdullahAlfaraj** [comment]
> i thinki got it. you must first generate some image with controlnet model, then mask popup
The mask/ preprocessed image is not available until you generate at least once. 
Though I admit it will be nice to have a way to preview the preprocessors's output before committing to a generation.
