### ISSUE TITLE
the ControlNet page is not content

### ISSUE THREAD

**Issue by wangweihua97** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#153]
![image](https://user-images.githubusercontent.com/37183388/224268827-567d09d6-32ab-4062-9546-1e1cb32be842.png)
My stable-diffusion-webui hava contronet plugin.
I use method 3 to  install plugin.
Click refresh button useless and other functions are normal

**Comment by AbdullahAlfaraj** [comment]
What photoshop version are you using?

**Comment by wangweihua97** [comment]
> v24.2.0

**Comment by AbdullahAlfaraj** [comment]
@wangweihua97 visit http://127.0.0.1:7860/docs
and check if you have the controlnet endpoints. 
![msedge_lEOHxouEPV](https://user-images.githubusercontent.com/7842232/224306891-82ca8c94-34d6-4c19-a7b7-141f8ab695b6.gif)

**Comment by wangweihua97** [comment]
> http://127.0.0.1:7860/docs



> @wangweihua97 visit http://127.0.0.1:7860/docs and check if you have the controlnet endpoints. ![msedge_lEOHxouEPV](https://user-images.githubusercontent.com/7842232/224306891-82ca8c94-34d6-4c19-a7b7-141f8ab695b6.gif) [ ![msedge_lEOHxouEPV](https://user-images.githubusercontent.com/7842232/224306891-82ca8c94-34d6-4c19-a7b7-141f8ab695b6.gif) ](https://user-images.githubusercontent.com/7842232/224306891-82ca8c94-34d6-4c19-a7b7-141f8ab695b6.gif) [ ](https://user-images.githubusercontent.com/7842232/224306891-82ca8c94-34d6-4c19-a7b7-141f8ab695b6.gif)

![image](https://user-images.githubusercontent.com/37183388/224340733-5a0c3f8d-b838-44a8-b368-7197251b1f94.png)
I found my controNet plugin no api contronet/model_list.
Maybe that's why, thank you

**Comment by wangweihua97** [comment]
> that could be the issue, make sure your `git pull`
> 
> 1. auto1111
> 2. controlnet extension
> 3. Auto-Photoshop-SD plugin, we have v1.2.1 available for method 3/UXP users

I re-download the auto1111 with git.
I used zip download before,unable to update.
The api controlnet/model_list Appeared.
![image](https://user-images.githubusercontent.com/37183388/224367038-f2fafd5c-4f08-49e0-8ee6-048732f0a8f8.png)
The page controlnet is displayed normally.
![image](https://user-images.githubusercontent.com/37183388/224368233-1087406b-ca78-4ed4-ab8c-13fab54f8e35.png)
thank you very much for your help
