### ISSUE TITLE
New functions recommended to add in the image2image mode.

### ISSUE THREAD

**Issue by mokalora** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#159]
Very nice plug-in. 
I like this more interactive drawing experience. 
It is suggested to add a preprocessing function of input image rotation in the image2image module, because the results generated from different angles for images such as faces vary greatly. 
At the same time, an option is recommended to add in the image2image generation with mask to let the user decide whether to delete the content beyond the mask. 
Thank you very much for your plug-in again, which avoids frequent image import and export.

**Comment by AbdullahAlfaraj** [comment]
Your second suggestion is great! Could you link me to a resource that explains the "preprocessing function of input image rotation" for image2img?

**Comment by mokalora** [comment]
> Your second suggestion is great! Could you link me to a resource that explains the "preprocessing function of input image rotation" for image2img?

When using image2image through this plugin, the incoming image is based on the orientation of the PS canvas, and it is inconvenient to adjust the orientation of the entire PS canvas. What I mean is that you can consider doing some simple preprocessing on the selected and incoming images, such as rotation and mirroring.

For example, when I use the WebUI to import images, I will use the screenshot tool to adjust the image to a more suitable angle for AI recognition, and then perform image2image. Specifically, I use Snipaste to take a screenshot, then paste it on the screen, rotate it, save it, and then import it into the WebUI.

**Comment by pastuh** [comment]
Suggestion is very simple:
Mask for each generated image must be attached all the time

+ Strange why I need to paint specific area with white color, If I already selected specific area with lasso tool..
