### ISSUE TITLE
Cannot connect to remote SD server

### ISSUE THREAD

**Issue by slayeryahu** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#160]
Resolve: Add --share --api for remote server connection

===================================
Hi, I found problem after I installed this plugin
My webUI is running and can use to generate image,
But the plugins still has red A at the top right corner.
I had --api added to the startup command line.

About install Environment:
Ps plugin was Installed from zip.(Guide 2) On windows OS
WebUI plugin was checkouted by git on the remote server.
Then open PS and  setting the url for sd.
click refresh.
It always said that:" autoxxxx backend is not runing"

but I  can use  browser webui  to generate image with that url.

![图片](https://user-images.githubusercontent.com/7860485/224528437-ea3af7e6-0a2c-460d-934e-c9eb66000bfb.png)
![图片](https://user-images.githubusercontent.com/7860485/224528446-25f95201-bdcf-466f-9fa1-ba4bb906b9b7.png)
![图片](https://user-images.githubusercontent.com/7860485/224528483-6825d1d2-2ae9-4a75-90eb-78381d763dab.png)

fix #160

**Comment by AbdullahAlfaraj** [comment]
Since you are running Auto1111 on a remote device you will need to add both command line arguments "--api --share"

**Comment by slayeryahu** [comment]
> 

Thank you,it works now! great job!

**Comment by theamazingfedex** [comment]
Update: I guess I reported my issue a tad too soon, but I found the solution; I just needed to set the SD url under the Settings tab of the plugin to be `http://127.0.0.1:8000` then refresh.

When using a remote instance of A1111, I needed to do the following:
1. Set the `SD_URL=http://192.168.86.86:7860` in the start_server.bat
2. Set the SD url in the Photoshop plugin under the Settings tab to `http://127.0.0.1:8000`
3. Refresh the Photoshop plugin from its main Stable Diffusion tab.

**Comment by AbdullahAlfaraj** [comment]
@theamazingfedex Actually you only need to change the sd url in the settings tab.
Also, no need to run the start_server.bat anymore. It's more convenient to install this repo as an extension in Auto1111, and it will run automatically whenever you run Auto1111.

**Comment by theamazingfedex** [comment]
@AbdullahAlfaraj my photoshop is running on a separate computer than Auto1111, so I think I still need to run start_server.bat in this plugin's folder in the photoshop install directory, or else it doesn't proxy correctly to the PC that's running Auto1111. Or did a change get pushed recently to simplify remote access?

**Comment by axthm** [comment]
When I deploy SD locally and set the SD plugin in Photoshop to use "127.0.0.1:7860," it can connect successfully. However, when I set the SD plugin in Photoshop to use a remote address, it fails to connect.

**Comment by axthm** [comment]
> 当我在本地部署 SD 并在 Photoshop 中将 SD 插件设置为使用“127.0.0.1：7860”时，它可以成功连接。但是，当我在 Photoshop 中将 SD 插件设置为使用远程地址时，它无法连接。

I can successfully access the remotely deployed SD page by visiting the remote address "192.168.0.254:7860" through a web browser.

**Comment by axthm** [comment]
> When I deploy SD locally and set the SD plugin in Photoshop to use "127.0.0.1:7860," it can connect successfully. However, when I set the SD plugin in Photoshop to use a remote address, it fails to connect.

I can successfully access the remotely deployed SD page by visiting the remote address "192.168.0.254:7860" through a web browser.
