### ISSUE TITLE
Problem: deprecated controlnet request params

### ISSUE THREAD

**Issue by TRGLN** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#162]
Hello, this is the problem:
Controlnet does not work after the last update of automatic1111 and controlnet.
![image](https://user-images.githubusercontent.com/113715629/224542448-acf293ad-0d31-4778-a5b3-65e238f63b8e.png)
When using ControlNet, the image is not displayed, an empty folder "session - *" is created in the layers
In the ControlNet tab in ViewMask, instead of a contour mask, an image generated by promt: "superhero art"
![image](https://user-images.githubusercontent.com/113715629/224543739-0a71920b-b283-4c25-86f1-50ed335f9287.png)

WebUI:
![image](https://user-images.githubusercontent.com/113715629/224543090-bd63c99d-e8ae-410e-a97e-c6e2c7569e2b.png)
installed extension:
![image](https://user-images.githubusercontent.com/113715629/224542953-9d2af4ff-c8bf-416f-9840-e45211a95f72.png)

win11
rtx 3090

**Comment by AbdullahAlfaraj** [comment]
There appears to be a problem with the most recent ControlNet API, see:  https://github.com/Mikubill/sd-webui-controlnet/issues/571

**Comment by AbdullahAlfaraj** [comment]
fixed in v1.2.2

**Comment by TRGLN** [comment]
@AbdullahAlfaraj 
I updated the plugin to version 1.2.2, also updated the extension. Controlnet warning no longer appears in the console, but unfortunately the problem persists. When ControlNet is enabled, no image is displayed. The mask is also not created. It looks as if the generated image on request just goes to the View Mask slot (ControlNet)

I checked everything several times, also updated xformers and torch, disabled antivirus, ran with different arguments, used different controlnet models and preprocessors, but the problem persists.

![image](https://user-images.githubusercontent.com/113715629/225156405-fa0399e8-162b-4f6c-94dd-55d5180bb517.png)
![image](https://user-images.githubusercontent.com/113715629/225156556-413c4b31-ba02-4e9a-aeb8-170d8dcf7f87.png)
![image](https://user-images.githubusercontent.com/113715629/225156590-da63e3e1-28cf-4b1f-9b72-23b463eb2388.png)

**Comment by AbdullahAlfaraj** [comment]
@TRGLN It's working fine on my end.
![image](https://user-images.githubusercontent.com/7842232/225185280-4ffe2acb-da80-4452-85e3-fb4733b3504d.png)

Can you screenshot your controlnet settings in automatic1111?
![image](https://user-images.githubusercontent.com/7842232/225186101-83240268-74a4-4b1b-915c-12463c24ec8d.png)

one thing you could do is, backup your controlnet models, delete the controlnet extension folder and reinstall it.

**Comment by AbdullahAlfaraj** [comment]
read the following to get it working: 
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/172

**Comment by TRGLN** [comment]
@AbdullahAlfaraj
Applied the settings as in the screenshot above, the problem persists.
Revert controlnet back to a previous version worked.
I will wait for the update, thank you for your hard work.
