### ISSUE TITLE
COMMANDLINE_ARGS does not contain --api, API won't be mounted

### ISSUE THREAD

**Issue by guangxinzhao** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#166]
On MAC M1,I have followed the tutorial to set up --api,but,
But the terminal show “COMMANDLINE_ARGS does not contain --api, API won't be mounted”
Auto-Photoshop-SD shows the result below,
The Plugin can't communicate with Automatic1111
Automatic1111 is running, but you forgot to add --api flag to the webui command flags。

**Comment by charliemagee** [comment]
> Hi @guangxinzhao,
> 
> I'm not familiar with the Mac setup, so I can't give you specific instructions but the errors is pretty much what there is to say here. Have you checked that your local Automatic1111 Web UI has been configured to include the --api startup option.
> 
> Like I said, I'm not a mac user but using a bit of guesswork I think you need to look at your webui-macos-env.sh and make sure that --api is here ![image](https://user-images.githubusercontent.com/7783232/225594618-a46b77d6-aefa-43f4-8afc-e66e0ff40a65.png)

I'm on Mac M1 as well. The line in my webui-macos-env.sh looks like this:
export COMMANDLINE_ARGS="--api --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate"

This helped, but still not there. Still not generating images. When I click the Generate Txt2Img button, all I get is the circle slash symbol and nothing happens.

I've got the /sdapi/v1/samplers showing.

**Comment by AbdullahAlfaraj** [comment]
@guangxinzhao @charliemagee you will need to add "--api" flag to ```webui-user.sh``` file if you are on macOS 

read this issue: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/134

**Comment by guangxinzhao** [comment]
> 你好@guangxinzhao,
> 
> 我不熟悉 Mac 设置，所以我不能给你具体的说明，但错误几乎就是这里要说的。您是否检查过您的本地 Automatic1111 Web UI 是否已配置为包含 --api 启动选项。
> 
> 就像我说的，我不是 mac 用户，但使用一些猜测我认为你需要查看你的 webui-macos-env.sh 并确保 --api 在这里 ![图像](https://user-images.githubusercontent.com/7783232/225594618-a46b77d6-aefa-43f4-8afc-e66e0ff40a65.png)

Thank you for solving the problem,

**Comment by guangxinzhao** [comment]
> > 你好@guangxinzhao,
> > 我不熟悉 Mac 设置，所以我不能给你具体的说明，但错误几乎就是这里要说的。您是否检查过您的本地 Automatic1111 Web UI 是否已配置为包含 --api 启动选项。
> > 就像我说的，我不是 mac 用户，但使用一些猜测我认为你需要查看你的 webui-macos-env.sh 并确保 --api 在这里![图像](https://user-images.githubusercontent.com/7783232/225594618-a46b77d6-aefa-43f4-8afc-e66e0ff40a65.png)
> 
> 我也在使用 Mac M1。我的 webui-macos-env.sh 中的行看起来像这样： export COMMANDLINE_ARGS="--api --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate"
> 
> 这有帮助，但仍然没有。仍然没有生成图像。当我单击生成 Txt2Img 按钮时，我得到的只是圆斜线符号，没有任何反应。
> 
> 我有 /sdapi/v1/samplers 显示。

![iShot_2023-03-21_12 42 58](https://user-images.githubusercontent.com/126586846/226519268-367f7626-0c8f-46c7-98bb-1bb291ef9bf2.png)
 Hello @charliemagee ,You can use it by writing --api in it like this
