### ISSUE TITLE
inpainting workflow in latest version?

### ISSUE THREAD

**Issue by annasophiachristianahahn** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#168]
Hello! I have been watching tutorials on YT for the plugin trying to figure out how to correctly inpaint-

I don't see this INIT MASK button anymore

what is the correct workflow for inpainting now?

Do we use traditional photoshop layer masks? or do we define the mask separately on a different layer?

do we paint the area we want inpainted white or black? does the mask need a background that is white or black OR is it enough just to paint on the area that I would like inpainted?

Is there a resource where the functionality of the plugin is better documented/the current implementation of the inpainting function is explained?

**Comment by AbdullahAlfaraj** [comment]
Tutorials are in the wiki section. 
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/126
