### ISSUE TITLE
Errors installing

### ISSUE THREAD

**Issue by billium99** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#17]
Hi - using Studio M1 Mac I can't seem to get passed the install process.

williamhenderson@Williams-Mac-Studio ~ % git clone https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git
Cloning into 'Auto-Photoshop-StableDiffusion-Plugin'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 75 (delta 31), reused 50 (delta 19), pack-reused 0
Receiving objects: 100% (75/75), 46.51 KiB | 835.00 KiB/s, done.
Resolving deltas: 100% (31/31), done.
williamhenderson@Williams-Mac-Studio ~ % cd ~/Auto-Photoshop-StableDiffusion-Plugin/
williamhenderson@Williams-Mac-Studio Auto-Photoshop-StableDiffusion-Plugin % sh start_server.sh
start_server.sh: line 6: python: command not found
start_server.sh: line 7: ./server_env/bin/activate: No such file or directory
williamhenderson@Williams-Mac-Studio Auto-Photoshop-StableDiffusion-Plugin % sh start_server.bat
start_server.bat: line 1: @REM: command not found
does server_env exist
start_server.bat: line 4: syntax error near unexpected token `('
start_server.bat: line 4: `if exist server_env\ ('

Am I doing something wrong here? BTW - starting with the bat file instead of trying to run the sh file doesn't make a difference.

Any advice would be appreciated. Love what you've created here!

**Comment by EkaMei** [comment]
This currently does not support macOS.

**Comment by AbdullahAlfaraj** [comment]
@billium99 the complaint seems to be about the command "python"
try using "python3" instead of "python"

**Comment by billium99** [comment]
Abdullah thank you - that made the difference!
