### ISSUE TITLE
First image disappears and controlNet_input_image not being sent to SD

### ISSUE THREAD

**Issue by BatmanNova** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#172]
potential continuation of #162 

I am no longer getting the deprecated controlnet error in the SD console but the output image of the img2txt prompts still does not resemble the input image.
![image](https://user-images.githubusercontent.com/35268584/225147109-c42332cd-e07d-47bc-9724-3532c1593487.png)

Adobe Photoshop Version: 24.2.1 
SD commit: commit: dfeee786
photoshop plugin version: 1.2.2

I'm having another issue where the first image of any generation txt2img disappears. As the first image is being generated I can see the live preview updating and the "temp_preview_image" layer being updated, but once the generation completes I am left with nothing, not even a new "Sessions" folder. It does however display in the "View Mask" image of controlnet.
![image](https://user-images.githubusercontent.com/35268584/225148079-52c35483-809d-4ee1-a5dc-9caf343b5405.png)
![image](https://user-images.githubusercontent.com/35268584/225148414-7e2b1998-b64e-4cb6-b7b7-23e33da5f33c.png)

If I generate more than 1 image, I get n-1 images in my viewer> viewer/history
![image](https://user-images.githubusercontent.com/35268584/225148616-fd15f3e6-e1e0-4eca-bb5b-8b3ece39dd0e.png)
![image](https://user-images.githubusercontent.com/35268584/225149251-65f58923-8d61-49ff-93c9-c5db23c4dc79.png) (the first image from the batch of 3 images showing in the Controlnet >"View Mask")

Let me know if there is a logging file or something I can attach to this that may help.

**Comment by AbdullahAlfaraj** [comment]
I've debugged the issues further. I found that controlnet is not longer functional in v1.2.2 (took about a day for it break)

if you still want to use it, do the following: 

1) navigate to the controlnet extension folder from within the cmd:

![image](https://user-images.githubusercontent.com/7842232/225191329-b7d5c187-f5a7-4ad3-836d-dbf0f8719aa3.png)

2) paste the following git command: 
```git checkout 6a5580ca7c144e04220d1e12c1e0cc92eca8bccb```
3) restart Automatic1111

This will revert controlnet to the point where it was working.

However, we'll fix it properly in an upcoming update

**Comment by BatmanNova** [comment]
Can confirm that reverting back to that controlnet commit worked, it also fixes the issue where I would get n - 1 images generated.

**Comment by BatmanNova** [comment]
Can confirm that reverting back to that controlnet commit worked, it also fixes the issue where I would get n - 1 images generated. 

edit: apologies I closed on accident; feel free to close now or when it gets fixed.
