### ISSUE TITLE
Extension cannot be installed，Asking for help

### ISSUE THREAD

**Issue by SevenKan** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#175]
WebUI said
“
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git clone -v https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git E:\Stable_Diffusion\tmp\Auto-Photoshop-StableDiffusion-Plugin stderr: 'fatal: destination path 'E:\Stable_Diffusion\tmp\Auto-Photoshop-StableDiffusion-Plugin' already exists and is not an empty directory. '
”

cmd said
“
Error completing request
Arguments: ('', 'https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git') {}
Traceback (most recent call last):
  File "E:\Stable_Diffusion\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\Stable_Diffusion\modules\ui_extensions.py", line 145, in install_extension_from_url
    repo = git.Repo.clone_from(url, tmpdir)
  File "E:\Stable_Diffusion\py310\lib\site-packages\git\repo\base.py", line 1148, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "E:\Stable_Diffusion\py310\lib\site-packages\git\repo\base.py", line 1086, in _clone
    finalize_process(proc, stderr=stderr)
  File "E:\Stable_Diffusion\py310\lib\site-packages\git\util.py", line 386, in finalize_process
    proc.wait(**kwargs)
  File "E:\Stable_Diffusion\py310\lib\site-packages\git\cmd.py", line 502, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git E:\Stable_Diffusion\tmp\Auto-Photoshop-StableDiffusion-Plugin
  stderr: 'fatal: destination path 'E:\Stable_Diffusion\tmp\Auto-Photoshop-StableDiffusion-Plugin' already exists and is not an empty directory.
'
”

**Comment by adunato** [comment]
Hi @SevenKan 
The issue suggests that the extension is already installed. I just tried to reinstall again and I get the same error, although I'm seeing it from the UI rather than the console.

First, how are you installing the extension? Web UI Extensions tab using the github link for this plugin or something else?

As the folder seems to exist already, have you checked the Extensions / Installed tab? If exists, you can update it from there (see below)

![image](https://user-images.githubusercontent.com/7783232/225592156-c76aed86-abb7-40a8-aeca-a7249093fa87.png)

**Comment by SevenKan** [comment]
i use Web UI Extensions tab to install this extension，Nothing in the installed list
![image](https://user-images.githubusercontent.com/37521990/225843802-67709ed2-52d1-4710-9883-d03bd8b1eb94.png)
![image](https://user-images.githubusercontent.com/37521990/225844069-a85aa26d-4da8-40fc-b33e-819e749650a7.png)

**Comment by SevenKan** [comment]
"local directory name" is empty，I don't fill in any information here.

Just tested to remove "Auto-Photoshop-StableDiffusion-Plugin" from tmp directory and install it again.

thank you very much
