### ISSUE TITLE
the command "show" is not currently available

### ISSUE THREAD

**Issue by jasonlok000** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#179]
![image](https://user-images.githubusercontent.com/83269161/225877275-1b018456-6acf-4e0e-9065-645fba105292.png)
As per title, this showed up when trying to generate an image.  Seems to cause random mis-alignments (Does not happen every single time, the problem dissapear after regenerating an image in the same session)
![image](https://user-images.githubusercontent.com/83269161/225878014-0db484fd-622e-46d6-80bc-44cc4b836110.png)

**Comment by adunato** [comment]
Thanks for the report. I think it's two separate (annoying) issues in my experience and neither is easy to reproduce, unfortunately. The photoshop error can happen if there is no white background set for the image (a photoshop requirement for the operation in progress), this should be added automatically by the plugin but there may be situations where this doesn't happen.

The misplacement of the generation happens on my setup quite randomly. Meanwhile, I use the Layer to Selection button (left of generate button) to realign it.

**Comment by AbdullahAlfaraj** [comment]
Need more information, can you screenshot the layers stack, both before and after hitting the generate button.
Also try to include the documents tab in the screenshot.

**Comment by jasonlok000** [comment]
I don't have my pc next to me right now, I'll do that on Monday!  Thank you
so much!!

**Comment by jasonlok000** [comment]
@adunato You are correct.  The issue appears when only the background layer is available by default, where it's usually locked.  I think the alignment thing is random.
![image](https://user-images.githubusercontent.com/83269161/226256435-4cadf6fa-b9ff-40fa-8562-8863b787aa9c.png)
