### ISSUE TITLE
Something is really wrong with the Inpainting.

### ISSUE THREAD

**Issue by ZeroCool22** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#180]
Take a look:

https://streamable.com/7lkgfh

Also, the extension for a "better" inpainting is installed and updated:

![Screenshot_7](https://user-images.githubusercontent.com/13344308/226068253-fa3cf41d-e968-441e-8d78-f2039dc21256.png)

As you can see inside the AUTO's plugin everything works fine but with the plugin...

**PD:** Using an inpainting model and DDIM Sampler.

**Comment by ZeroCool22** [comment]
Working fine now.

![Screenshot_8](https://user-images.githubusercontent.com/13344308/226070119-1c2d03e1-eba4-4d7f-83b4-319e138a5437.png)

**Comment by karasuuuuu** [comment]
How did you fix this? Having the same issue

**Comment by ZeroCool22** [comment]
> How did you fix this? Having the same issue

I didn't do anything really, be sure to be on the generated layer.

**Comment by Renaldas111** [comment]
You were inpainting at very low resolution (~200*200), SD is very bad at these resolutions. But, at least, you have inpainting working properly, mine is not working.
