### ISSUE TITLE
Please leave the opacity of the created mask at 100%.

### ISSUE THREAD

**Issue by ZeroCool22** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#181]
I't really annoying to be changing back to 100% every time.

![Screenshot_9](https://user-images.githubusercontent.com/13344308/226070918-9aebd32c-16e9-454e-a58f-4aec0dec3c6b.png)

I put it back at 100% but would be nice if come like this by default.

**Comment by AbdullahAlfaraj** [comment]
you don't need to change it back 100%. the plugin does that internally.
Or you can completely ignore the temp layer, and just paint the mask on your own layer.
