### ISSUE TITLE
Error: Exception in ASGI application; & json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by mynovmbr** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#20]
Hi, after a long journey finally got everything installed with no errors, however when I test using the default "cute cat" I got following "Exception in ASGI application" I checked the other ASGI exception but seems we are facing the different problems:

> [32mINFO[0m:     Waiting for application startup.
> [32mINFO[0m:     Application startup complete.
> txt2ImgHandle:
> 
> payload:  {'prompt': 'cute cat', 'negative_prompt': '', 'steps': '20', 'sampler_index': 'Euler a', 'width': 512, 'height': 512, 'batch_size': '1', 'cfg_scale': 7, 'seed': '-1', 'mask_blur': 0, 'use_prompt_shortcut': True}
> raw_keywords:  []
> strip_keywords:  []
> original_substrings:  []
> final text:  cute cat
> raw_keywords:  []
> strip_keywords:  []
> original_substrings:  []
> final text:
> [32mINFO[0m:     127.0.0.1:49698 - "[1mPOST /txt2img/ HTTP/1.1[0m" [91m500 Internal Server Error[0m
> [31mERROR[0m:    Exception in ASGI application
> Traceback (most recent call last):
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
>     return await self.app(scope, receive, send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\applications.py", line 270, in __call__
>     await super().__call__(scope, receive, send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\applications.py", line 124, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
>     raise exc
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
>     raise exc
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
>     raise e
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\routing.py", line 706, in __call__
>     await route.handle(scope, receive, send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\starlette\routing.py", line 66, in app
>     response = await func(request)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\routing.py", line 235, in app
>     raw_response = await run_endpoint_function(
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
>     return await dependant.call(**values)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server\python_server\.\serverMain.py", line 106, in txt2ImgHandle
>     dir_name,image_paths = await txt2ImgRequest(payload)
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server\python_server\.\serverMain.py", line 36, in txt2ImgRequest
>     r = response.json()
>   File "D:\_RandomDots\Auto-Photoshop-StableDiffusion-Plugin\server_env\lib\site-packages\httpx\_models.py", line 751, in json
>     return jsonlib.loads(self.content.decode(encoding), **kwargs)
>   File "C:\Users\shiyi\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\shiyi\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\shiyi\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> [32mINFO[0m:     127.0.0.1:49705 - "[1mGET /sdapi/v1/progress?skip_current_image=false HTTP/1.1[0m" [32m200 OK[0m

**Comment by EkaMei** [comment]
Can you show us the Automatic1111 console output? Did Automatic got the web request?

**Comment by mynovmbr** [comment]
> Can you show us the Automatic1111 console output? Did Automatic got the web request?

Thanks for prompt reply, Automatic1111 console logs nothing:
![image](https://user-images.githubusercontent.com/10234287/209419911-6be6443b-21a5-403e-8447-49997f43b8b2.png)

**Comment by EkaMei** [comment]
Yup, looks like for whatever reason the PS plugin can't reach the automatic installation at all. Not really sure where to go from here.

We might have to increase the tracing level to find out how to trouble shoot this kinda issue in a later version.

**Comment by AbdullahAlfaraj** [comment]
@mynovmbr , can you tell us which version of the plugin you are using?
it will probably be a good idea to make it visible to the user to see if a successful connection has been established between the plugin and auto1111 server.

but for now, the easiest way to check if there is a connection, is to hit the Refresh button. this will send a simple request to auto1111's server to get the list of models. tell us if you are getting error when doing that.
