### ISSUE TITLE
how does upscaling work?

### ISSUE THREAD

**Issue by tonnotonnu** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#203]
using the upscale in photoshop OSX

selected the layer with the picture that i'd like to upscale

and then i did the upscale

but the result is identical to the unupscaled picture

the output is also the exactly same size

am i missing anything?

**Comment by AbdullahAlfaraj** [comment]
the result mostly depends on the upscaler model.
try downloading ```realesrgan_x4plus``` upscaler model for better result.

![image](https://user-images.githubusercontent.com/7842232/229310886-e28a89f2-60b4-49a0-aeaa-682d658eefff.png)

**Comment by simon-pabst** [comment]
Hey @AbdullahAlfaraj , I don't think this has been answered - I just ran into the same question and can't find anything on the wiki or in other issues. Any hints would be greatly appreciated!

How is this feature supposed to work?
I select a 512x512 area and hit Generate Upscale with my favourite upscaler active and Resize set to 2.0x.
The output is 512x512 on a new layer. The expectation is that it would be a 1024x1024 image (upscaled 2x), not 512x512. What are we missing here?

**Comment by AbdullahAlfaraj** [comment]
@simon-pabst the output image in your case is 1024x1024 imported as a smart object, and then scaled down to fit the selection area, which I'm assuming is 512x512.
you can check native resolution of smart object in two ways:
- Select the output image in the layer stack and double click the thumbnail, this will open the image in a new document in its native resolution which 1024x1024.
- Go to settings tab click on "Get Path" button to find directory where the images are stored at. find your output image and check its resolution.

**Comment by MicahBurke** [comment]
@AbdullahAlfaraj 

> Select the output image in the layer stack and double click the thumbnail, this will open the image in a new document in its native resolution which 1024x1024.

This is not working see example video here:
https://burkephotography.tinytake.com/msc/ODU4OTExNF8yMTkzODY4OQ

Original image is 2048x3098, using ESRGAN_4x and a resize of 2 or 3, the image is _smaller_, though it has more noise.
The image size is 1352x2048...
