### ISSUE TITLE
Not working in mac

### ISSUE THREAD

**Issue by vonvanzu** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#208]
I put the zip file in the plugging and is not available pluggin. It would be great working for mac. thanks.

**Comment by krummrey** [comment]
Same here. Photoshop Version 23.5.5 - On a corporate managed account. Is there something admins can disable that would prevent it from working?

**Comment by vonvanzu** [comment]
I have photoshop 2022, so dont work on it?

**Comment by AbdullahAlfaraj** [comment]
two things to keep in mind:
1) you need photoshop 24.0 or higher
2) you need to unzip zipped file and place the newly created folder in the adobe's plugging folder
