### ISSUE TITLE
Outpaint not working properly

### ISSUE THREAD

**Issue by kamerosoul** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#211]
Please take a look at picture of outpaint settings. I have tried several times just to generate cropped hand but I have strange results.
Your comments will help me to understand better.
Thanks.
![Capture](https://user-images.githubusercontent.com/58159710/229441340-180fe03f-a384-4dba-bfcf-de156f1ddc60.PNG)

**Comment by AbdullahAlfaraj** [comment]
The settings you are using are not optimal for outpainting
You'll need to increase the denoising noise to 0.92 and change mask content to "latent noise." 
Or just select the latent noise preset from the "smart preset" dropdown menu.

**Comment by kamerosoul** [comment]
Thank you
