### ISSUE TITLE
cant generate my first image

### ISSUE THREAD

**Issue by sxddart** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#215]
i ired installing the plugin via Unzip method but culdt see it in the plugin tab
So i installed the plugin successfully with the first method and got the UI to work but when I hit txt to image this message pops up. Someone, please help me out

**Comment by sxddart** [comment]
![2023-04-06](https://user-images.githubusercontent.com/130000868/230214419-62d7f529-3a1c-4c29-85e3-60f692d5580c.png)

**Comment by AbdullahAlfaraj** [comment]
It seems the stable horde has added a limit to the length of your prompt. Remove the keyword "{ugly}" from the negative prompt to avoid the error.

Keep in mind "{ugly}" is a special keyword that represent more than 30 other words, therefore it is considered long.
