### ISSUE TITLE
plugin shows v0.0.0

### ISSUE THREAD

**Issue by rbisrxx85** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#217]
Hello,

I came back to use the AI plugin after a few months and when i open, I see the plugin version says v0.0.0 - I tried running start_server.bat in the plugin folder, but when i open photoshop and the plugin its still showing v0.0.0

![image](https://user-images.githubusercontent.com/5204554/230431882-0203a647-cfe4-40a7-a6cf-aa9c959d3639.png)

Looking forward to the assistance!

**Comment by AbdullahAlfaraj** [comment]
This seems to be an old version, before we've separated the outpain mode from the inpaint tab
read https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/213#issuecomment-1497766372 for instruction on updating the uxp version of the plugin 
or reinstall the plugin through [the one click installer](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#method-1-one-click-installer)
