### ISSUE TITLE
Understand how to use controlnet with the plugin

### ISSUE THREAD

**Issue by AbzAlona** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#223]
Hello,
I've used controlnet with no problems from the webui, however I can't get it to work in the plugin. I always get the error "You need to select a valid Controlnet module". I have everything updated and the videos I see do not clarify anything. Can someone give me a mini-tutorial on how to use it?
Thanks.

**Comment by CraigFedynich** [comment]
With the part of the image you want to use selected, on the controlnet tab: check enable, click set controlnet (which will take the selection to use for control net), select the left dropdown box as your preprocessor (used if you aren't already using a preprocessed controlnet image), and right dropdown box select the controlnet model. Adjust weight as needed using the slider. It should use controlnet on the next generation. You can generate a layer with the controlnet image by clicking on "view mask". Sometimes I use that to save it or move it's location as needed. Guess mode is encouraged as with normal controlnet.

**Comment by AbzAlona** [comment]
Thanks for the explanation CraigFedynich!
