### ISSUE TITLE
Seems I need to have kudos to use this plugin? Confused?!?

### ISSUE THREAD

**Issue by sandra90L** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#227]
<img width="588" alt="Screenshot 2023-04-15 at 13 13 28" src="https://user-images.githubusercontent.com/130840792/232222585-9c4de81b-aab3-4352-a9ce-8ba18cb3bec0.png">
Hello! I've installed in 1 click the plugin but seems I can't use it?
Can someone help please?

**Comment by AbdullahAlfaraj** [comment]
The plugin doesn't require any form of credit, read this to resolve the error: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/215#issuecomment-1499185806
