### ISSUE TITLE
Not working with 1.2.3 

### ISSUE THREAD

**Issue by zmvz11** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#254]
dont know why it says this

response -> uni_pc_lower_order_final
  value is not None (type=type_error.not_none)

**Comment by AbdullahAlfaraj** [comment]
@zmvz11 hard to tell without much info, but maybe it's related to this issue: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/251#issuecomment-1541991512

**Comment by zmvz11** [comment]
Thank you
