### ISSUE TITLE
v1.2.3 ControlNet not utilized in Txt2Img generation, but no errors apparent

### ISSUE THREAD

**Issue by concescu** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#261]
Tremendous work with this plugin! @AbdullahAlfaraj, thank you very much for creating this tool and responding to issues here. I am hoping to have my issue easily resolved: I can generate Txt2Img with the plugin without problems, but when I enable ControlNet in the plugin, it seems to have no impact on the images generated. They continue to have random compositions, but there also are no errors being thrown in the CMD screen. This issue does not come up when running ControlNet within Automatic1111.

I installed the plugin with Auto.Photoshop.SD.plugin_v1.2.3.CCX. I am running Photoshop release 24.4.1. Please see Automatic1111 version and other component versions below.

![0_Automatic1111 version](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/67158334/6bac7798-04aa-4f56-8a96-5a1d2e3abf87)

Below are ControlNet settings in Automatic1111, which correctly uses the canny edges to maintain the composition:
![1_ControlNet Settigns in Automatic1111](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/67158334/3db8ec4c-6a2d-4647-8525-af596a67dd7c)
![2_ControlNet working inside Automatic1111](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/67158334/3cb78b35-2fb4-41c6-9948-544eb493902a)

Below are ControlNet settings in the PS plugin, same input image with correct canny edge detection:
![3_ControlNet setup in Auto-Photoshop-SD](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/67158334/ed12fcca-58dd-4e8c-b5d4-7fb0ecf6b857)

When I click "Generate Txt2IMG", a new image without the canny edges composition is created:
![4_ControlNet not utilizing Auto-Photoshop-SD](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/67158334/268057ff-3b5e-4b5e-a1a9-027b3ac74c31)

The CMD window shows ControlNet being called differently (perhaps by your design), but no errors are thrown by the script.
![5_CMD Screenshot for Auto-Photoshop-SD](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/67158334/e3312c15-7f0f-4524-89d0-b00dc3446ab5)

How can this be solved? Is it an issue due to different version numbers, or something else entirely?

Best,
Cristian

**Comment by concescu** [comment]
Problem solved, Automatic1111 had not been updated to version 1.2.1. ControlNet works correctly now.

**Comment by AbdullahAlfaraj** [comment]
@concescu 
I’m glad to hear that you were able to solve the problem and thank you for reporting the solution back.
Also, keep in mind that interrupting a ControlNet request while the preprocessor is still loading can sometimes cause similar issues. In that case, the only solution is to restart Auto1111. There is no need to restart the plugin as this is caused by the ControlNet extension.
