### ISSUE TITLE
COMMANDLINE_ARGS does not contain --api, API won't be mounted - Windows. 

### ISSUE THREAD

**Issue by zeuszl1** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#279]
Hey all, i know this is probably a topic that has been posted a lot but im just wondering if anyone can assist me with this issue as well. 

I downloaded everything correctly I believe, got the Server Running for Auto-Photoshop-StableDiffusion-Plugin
![Auto-Photoshop-StableDiffusion-Plugin](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/129636022/287b66d3-d4b4-4fca-b8f2-a99dab37c830)

Shows - Application startup complete.

But when going to Stable Diffusion, im getting this error COMMANDLINE_ARGS does not contain --api, API won't be mounted
![StableDiffusion](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/129636022/be5dc6b3-a46b-4458-ab3f-1be725e60278)

screenshot added 

Ive done some research and noted that people were editing the "WebUI-User.bat" field, as I did below 
![Screenshot 2023-05-26 212435](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/129636022/f54fe224-dbec-44f8-8aa3-8d3f6aac639b)

I also edited the WebUI-User.sh as well with the included arguments as below. 
![Screenshot 2023-05-26 212645](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/129636022/e35dd6a7-742b-410d-868b-e272bfe66c8b)

Launching the Plugin seems to work, but i cant actually Interact with it. pressing on any settings do nothing other than "Update" showing the plugin is up to date. 
I cant click on settings, extras, viewer etc. 
![Screenshot 2023-05-26 213359](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/129636022/e3d4c859-d0ea-468c-8636-0e24154dbca6)

If anyone is willing to help me, much appreciated.

**Comment by AbdullahAlfaraj** [comment]
It looks like you've installed the plugin using method 3, which is intended for developers or those who want to modify the source code. I recommend using method 1 (.ccx) or method 2 (.zip) instead. These methods are quick to install and the plugin will remain permanently inside Photoshop without the need to run any server.

**Comment by zeuszl1** [comment]
> It looks like you've installed the plugin using method 3, which is intended for developers or those who want to modify the source code. I recommend using method 1 (.ccx) or method 2 (.zip) instead. These methods are quick to install and the plugin will remain permanently inside Photoshop without the need to run any server.

I believe i had to use the 3rd version due to having another "copy" of photoshop, ill keep doing some troubleshooting. i just finished installing Node for the "npm install" portion

**Comment by zeuszl1** [comment]
Update: 
After running "npm run watch" i got this readout 
![Screenshot 2023-05-26 221306](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/129636022/62f5b0a2-49f2-4b62-b455-1ff8be47ad38)

Launched the Plugin Server + A1111 but still getting the mount error.

**Comment by zeuszl1** [comment]
Restarted the computer. 

Ran npm install + npm run watch via CMD inside of AutoPhotoshop Plugin root 
Launched the Plugin Server - Application startup complete.
re-added set COMMANDLINE_ARGS= --api via webui-user.bat, saved. 
Ran webui-user.bat

Launching Web UI with arguments: --api - WORKING! 

Launched Photoshop 
Launched Adobe UXP Developer Tool
Loaded Plug-in 

Tested Plugin 
Reolved.

**Comment by zeuszl1** [comment]
If there is a faster way to get all this up and running via Dev version please let me know!

**Comment by AbdullahAlfaraj** [comment]
> If there is a faster way to get all this up and running via Dev version please let me know!

You will need to run ```npm run watch``` or ```npm run build``` only once every time you update via ```git pull```

But this how I run the plugin using the uxp method: 
Launched Photoshop
Launched Adobe UXP Developer Tool
Load the Plugin
