### ISSUE TITLE
cannot enter any text into text fields

### ISSUE THREAD

**Issue by mjalb** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#282]
Hi,

I am very much willing to buy you a round of coffees for your great work!

Unforunately, I am facing an issue: Using Photoshop 24.5 and the most recent plugin version here from Github (most current one according to the plugin itself), I cannot enter any text into the plugin's text fields. When I click into any of the input fields (prompt fields), the border flashes blue, no cursor appears and all keyboard input is piped through to Photoshop itself. It looks like input focus is not set to the plugin's panel. This is running Windows 11.

Any idea what might be going on? Thanks!

**Comment by mjalb** [comment]
Some more information: It seems the problem is connected to me using a remote webui instance. I guess you can reproduce the issue by NOT starting webui before activating the plugin. It will then complain about webui not being available - and remove the sample text from the text input fields. After that, you should be in the situation I am in.
I can easily use webui remote from the plugin by giving the correct web path in the settings - THAT is working. But I cannot re-activate the text fields once the sample cat-text has been removed.

**Comment by mjalb** [comment]
Update: Upon further testing, the error is tied to specific panel SIZES. Carefully resizing the panel by single pixels will make it work - and then work not. Makes the interface hard to use, but at least this points towards it being a Photoshop issue, not so much a plugin thing?

**Comment by AbdullahAlfaraj** [comment]
@mjalb can you provide a screenshot? 
All of UXP based photoshop plugin have these types of issues:
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/4ff11a2d-b614-4e9a-be46-4f57f90795a3

**Comment by mjalb** [comment]
here's a screen capture showcasing the issue:

[https://i.ibb.co/MfTjBdW/nogood.gif](url)

I can "work" with it (cannot drag the panel open to more than about 20% of my screen), but it's tricky.

**Comment by AbdullahAlfaraj** [comment]
This is having been solved in v1.2.6
