### ISSUE TITLE
Plugin icon

### ISSUE THREAD

**Issue by Ypdes** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#283]
Hey everyone, 

Sorry, I know it's a bit stupid. But is there an icon of this plugin? I mean for the toolbar? Because Stable.Art has. 

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/134853152/fbfdb9bd-7b0b-4157-8045-c3ee3f8fecb5)

**Comment by AbdullahAlfaraj** [comment]
Thank you for bringing it to my attention.
I've fixed it and will repackage it in .ccx file in v1.2.6

**Comment by Ypdes** [comment]
> Thank you for bringing it to my attention. I've fixed it and will repackage it in .ccx file in v1.2.6

You're welcome. You're as fast as light. I'm looking forward to 1.2.6

**Comment by Ypdes** [comment]
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/134853152/dda58dc9-2bb4-488e-bb79-b1b69a8e1aba)
