### ISSUE TITLE
controlnet reference model doesnt work

### ISSUE THREAD

**Issue by heartlocket** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#286]
the new controlnet reference only mode doesn't work. instead the plugin prompts to add a model name, but this new mode just uses the reference preprocessor without a controlnet model

**Comment by AbdullahAlfaraj** [comment]
This has been fixed in v1.2.5
I will release .ccx file to the public in few days.

**Comment by AbdullahAlfaraj** [comment]
v1.2.5 has been released, so I'm closing this issue.
