### ISSUE TITLE
[Question]: CN Inapinting: Is this workflow possible anytime soon?

### ISSUE THREAD

**Issue by Woisek** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#295]
Like shown here in A1111 -> https://www.youtube.com/watch?v=ot5GkaxHPzk but done in Photoshop? This would be awesome!

**Comment by AbdullahAlfaraj** [comment]
Yes, this is available in v1.2.6

**Comment by Woisek** [comment]
Great! Thanks, will check it out! 👍
