### ISSUE TITLE
Infinite memory usage.

### ISSUE THREAD

**Issue by zhaodice** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#299]
sometimes works fine,but when I edit promopt to others, PS will use too many memory until system error.
![QQ图片20230604141823](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/63996691/e2988bc7-ecba-4985-a989-8add98de9cef)

![QQ图片20230604141836](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/63996691/18356317-1e95-44b1-a0ae-1a4ec050a53a)

My computer memory is 16GB and Photoshop has taken 10GB or more when I select whole section and click text2image generate

**Comment by zombieyang** [comment]
how large is it?
