### ISSUE TITLE
How to use this using remote server?

### ISSUE THREAD

**Issue by ambiSk** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#3]
I have setup a remote server and have installed A1111 on it, how can I use that remote server A1111 over here?

**Comment by AbdullahAlfaraj** [comment]
find your Automatic1111 ip and port,  it's the same address you use to access the auto webui from browser.
you will have to change all instances of 
```
"http://127.0.0.1:7860/"
``` 
in the code base to the new address.

**Comment by Kyxsune** [comment]
#7 (just closing the loop, pretty sure OP has seen it already)

**Comment by sphuff** [comment]
Just opened a PR: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/pull/8

**Comment by AbdullahAlfaraj** [comment]
I just merge #8 into master. 
you just need to edit the start_server.bat with your's auto1111 ip address and port.
