### ISSUE TITLE
Once again about inpainting, impossible to understand how to do this

### ISSUE THREAD

**Issue by Renaldas111** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#300]
Several months ago I gave up trying to understand this plugin as I was not able to grasp how is inpainting performed here.
Today I tried again, as the plugin improved in last months, and I was in a hope I will be able to perform inpainting. No, still mission impossible for me.
Can anybody write a short explanation, how is inpainting done in this plugin.
I open a picture in PS. Guide me step by step like I'm 5 years old, what and where should I press to be able to work with inpainting. I am stuck immediately at the beginning, I my brain refuses to understand what should I do after I open a picture. Where should I draw a mask, on a top of a layer in which I opened the picture?

**Comment by 4DeepThought2** [comment]
Yep, try changing all the settings 100 times, move things around with hand waves, close open, retry.  Finally on the 47th time it'll work.

**Comment by Renaldas111** [comment]
Thanks for sarcasm, 4DT2 :)
Unfortunately, despite successfully inpainted probably up to 10K images in webui, I still struggle to understand how to do this in this plugin. And inpainting in PS will surely be more convenient in comparison to inpainting directly in webui.
So, am I the only one so dumb, who was not able to grasp inpainting in this plugin in several months?

**Comment by AbdullahAlfaraj** [comment]
@Renaldas111, Follow the instruction in this comment, https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/178#issuecomment-1579500105
