### ISSUE TITLE
Unable to select Lora

### ISSUE THREAD

**Issue by a3393009943** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#306]
Auto.Photoshop.SD.plugin_v1.2.5.zip
The version displayed in ps2023 is still v1.2.4, and Lora cannot be selected, and the SD switch to the stable version still has no effect
[https://pic.peo.pw/a/2023/06/08/6481a6ff8fd26.png](url)

**Comment by AbdullahAlfaraj** [comment]
You’re using version 1.2.4. In that version, you’ll need to install the Auto-Photoshop-SD extension in Automatic1111 to access the Lora list. You can find instructions on how to do that in Method 1. In version 1.2.5, we use the newly implemented Lora API to access the list but still I recommend installing the extension as it gives you access to other features, like mask expansion and image search.
