### ISSUE TITLE
Can't install the plugin on the Photoshop Beta version

### ISSUE THREAD

**Issue by thiagojramos** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#307]
I downloaded the .ccx file from the release, but when I open it, it just opens a PowerShell window and closes immediately. Even after a "clean" installation of Adobe Creative Cloud, the same thing happens. I managed to do it once using method 3, but it's not very convenient for me to have to open multiple programs every time I want to use Photoshop.

Thanks for the plugin.

**Comment by ZeroCool22** [comment]
Download the ZIP one option and put the folder here:

![Screenshot_6](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/13344308/ccf5a9a3-51e4-4489-8d11-1f0fea3307d4)

**Comment by thiagojramos** [comment]
So there's no way to use the .ccx then?
