### ISSUE TITLE
Only masked option when inpainting

### ISSUE THREAD

**Issue by geangs** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#309]
Is there a way to do something similar to the "only masked" option available on automatic1111 when inpainting?

**Comment by AbdullahAlfaraj** [comment]
Yes, it’s called Inpaint at full resolution. I believe the new naming convention is ‘Only Mask Option’. We still use the old one though.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/f0b5c836-9ed9-49fb-99c2-7e2ec1e52d3c)
