### ISSUE TITLE
Image for IMG2IMG wont change

### ISSUE THREAD

**Issue by Mr-Beakers** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#315]
Everything worked fine when I first installed the plugin, but after experimenting for a while, I discovered that I am no longer able to change any sourced image. Both the IMG2IMG and masking features are now fixed to a single image, and none of my attempts have been successful in resolving this issue. I have tried starting new projects and even reinstalling the plugin, but the problem persists. Although I can attempt to set the Init and mask images, it seems that these options have no effect. A feature unannounced to me might be at fault, but nothing I've done has fixed it.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/95188670/fdaffc78-f4cc-4de4-b313-65b1a6e6c857)

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/95188670/d276a28b-9740-40cd-9bf8-0c651573684e)

**Comment by Mr-Beakers** [comment]
ignore the random images, that's just what I had on my HDD when testing this out.

**Comment by AbdullahAlfaraj** [comment]
0.1 is a very low denoising strength value.
Here is an example of how increasing the denoising strength will increase the variation of the generated images.
 
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/4d53a862-f9f3-418c-b1df-791d66f31e32)

The wiki has a guide about how to use the plugin, I'd recommend reading. 
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/wiki#generate-an-img2img

**Comment by Mr-Beakers** [comment]
> 0.1 is a very low denoising strength value. Here is an example of how increasing the denoising strength will increase the variation of the generated images.
> 
> ![image](https://user-images.githubusercontent.com/7842232/246049432-4d53a862-f9f3-418c-b1df-791d66f31e32.png)
> 
> The wiki has a guide about how to use the plugin, I'd recommend reading. https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/wiki#generate-an-img2img

I appreciate your response, but unfortunately, it doesn't solve my problem. I am well acquainted with stable diffusion. My issue is that in situations where I would typically drag an image to the UI, such as for img2img or in painting, i can't do that in this plugin. Initially, I was able to change it, but I have lost that capability. Any adjustments made to the normal stable diffusion settings still result in the same couch photo being modified. My problem stems from either my incompetence of this plugin or some fault in the software, not stable diffusion.

**Comment by AbdullahAlfaraj** [comment]
To change the initial image, end the session and select a new image before clicking generate.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/cf12bec1-cb39-4106-a4fd-efb872596101)

Another option if you click the pen button, the output image will be used as the initial image for future generations.
 

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/6115ae90-efb3-4a96-80ca-8daed16031c7)

**Comment by eimiss** [comment]
What do you mean by end the session? Because for me I don't even have that specific image anywhere around anymore. I open the full clean new tab, restarted photoshop and automatic1111 ui and I still have the problem, where the img2img, inpainting and outpainting gets the old image and do the inpainting from it.

**Comment by eimiss** [comment]
I also get this error after first running generate:
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/83466779/f82ad57a-14b0-4b6b-b79e-f187a6d6a337)

**Comment by Obeluss** [comment]
Hi, not sure if this helps or not, but I think i got the same issue, sometimes when i click Init image, It loads init from previews session. Its hard to recreate this issue on purpose, but I think it often happened when I open some older PSD. I work around by Marging layers, saving and open  with new psd.

**Comment by lour9987** [comment]
Same problem, after show error  (PS can't show, can't move or fetch error) I'm not able to pick the IMG2IMG Init image.
Just see if I open another proyect I could pick init image again

**Comment by KatieWebb** [comment]
I'm having the same problem. I tried uninstalling and reinstalling the plugin. What files do I need to delete to clear the cache or what ever?

**Comment by AbdullahAlfaraj** [comment]
> I'm having the same problem. I tried uninstalling and reinstalling the plugin. What files do I need to delete to clear the cache or what ever?

I'm not sure which problem you are referring to? can you describe it in more details? 
but uninstalling the plugin should be enough to clear plugin's data files.
