### ISSUE TITLE
Notification: scheduled to be listied on stable diffusion webui extension index

### ISSUE THREAD

**Issue by w-e-w** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#327]
Hi, I'm one of the maintainers of stable diffusion webui extensions index
I intend to add this project to the index if no objection is raised
see PR https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/117
```json
{
    "name": "Auto-Photoshop-StableDiffusion-Plugin",
    "url": "https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git",
    "description": "Adds API routs for Auto-Photoshop-StableDiffusion-Plugin",
    "tags": [
        "script"
    ]
}
```
if you wish to not have this listed on the extension index or make any changes to the descriptions or tags, please leave a comment or open a new pull request before 7/14

**Comment by AbdullahAlfaraj** [comment]
Thank you for considering this repository. I appreciate it and have no objections. 
However, I believe there may be a typo in ```routes```.

**Comment by w-e-w** [comment]
facepalm
it's merged
