### ISSUE TITLE
Smart Object setting not work ( 1.3.0 ) 

### ISSUE THREAD

**Issue by TRGLN** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#333]
In the new version 1.3.0, when the checkbox is unchecked, the image continues to be created as a smart object.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/113715629/e3e54155-59ef-4b66-9c8e-f0b308a6c5ca)

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
Launching Web UI with arguments: --xformers --api

P.S: Thanks a lot for 1.3.0, many great changes.

**Comment by AbdullahAlfaraj** [comment]
>In the new version 1.3.0, when the checkbox is unchecked, the image continues to be created as a smart object.

Yes, that's a bug will fix it soon in v1.3.1

Can you help me reproduce this bug in your image? We had to remove some features to fix it, so I’m surprised to see the shrinking/misalignment issue in your screenshot. Some helpful information would be the width and height sliders, as well as the selection area’s width and height. If you can reproduce it consistently, could you send me a small PDF file? Thanks!
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/2353e7e3-97f3-460a-bbea-23e644e35825)

**Comment by TRGLN** [comment]
I didn’t have any problems with the shrinking/misalignment.
I probably tried to generate in different modes (txt2img, img2img), randomly highlighting with a frame.
I didn't have this problem.
