### ISSUE TITLE
Allow AUTO_UPDATE to be set once again

### ISSUE THREAD

**Issue by RaXorX** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#343]
Allow auto update setting to be changed without having to change the install.py.

**Comment by AbdullahAlfaraj** [comment]
Why do you need to turn off the auto-update? What problems would it solve?

**Comment by RaXorX** [comment]
> Why do you need to turn off the auto-update? What problems would it solve?

It tries to redownload all the requirements at startup, or so the log says that it's checking for them. If it only looks for the update, then that's fine, but if it's reinstalling all the requirements that's different. Lately for that I've been using the --skip-instal arg unless that should solve the auto updating. 

Secondly, I'd rather prefer to manually update, being caution about bugs and breaks in new versions, I'd rather keep the currently working as is.

**Comment by rexcnxie** [comment]
I have same problem, Please fix it.

**Comment by AbdullahAlfaraj** [comment]
the auto-update function will check for an update on startup, but it will only update if an update is available.
