### ISSUE TITLE
[Feature Request] Implement Config Presets

### ISSUE THREAD

**Issue by RaXorX** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#345]
Ability to load config presets would be awesome.
Though not really sure what all it would load back in Photoshop's plugin since it can save in pretty much anything from the UI settings.

**Comment by huchenlei** [comment]
If you use photopea (Browser version replacement of Photoshop), the plugin `stable-diffusion-ps-pea` does offer the config preset. You can fully customize the A1111 payload using the config preset system.

See https://github.com/huchenlei/stable-diffusion-ps-pea#features `Config System` section.

Please give it a try and I would like some feedback on the config system design. Thanks!

**Comment by AbdullahAlfaraj** [comment]
@huchenlei I’ll check out your project when I have some time. But also, feel free to contribute to this project if you want.

@RaXorX do you mean like custom presets? https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/220#issuecomment-1500966379

**Comment by RaXorX** [comment]
> @RaXorX do you mean like custom presets? [#220 (comment)](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/220#issuecomment-1500966379)

Dang yeah :), that's what I meant actually. I noticed that option but wasn't really sure how to use it. Perhaps an option to actually save from the plugin itself. Manually doing that, that's something I didn't expect to do 😅
