### ISSUE TITLE
After installing Auto.Photoshop.SD.plugin_v1.3.0, I launch photoshop beta v25 and it shows: An unrecoverable error has occurred and Photoshop will now quit

### ISSUE THREAD

**Issue by jaceda** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#356]
Dear Sir,

I am writing to you today to ask for help in removing the Auto.Photoshop.SD.plugin_v1.3.0 plugin from my Photoshop beta v25. I installed the plugin using method 1, as described in the attached document. After installing the plugin, Photoshop beta v25 would not open. However, Photoshop v24.7 still opened normally. If I downgraded Photoshop beta to v24.7, it would also open normally.
![error](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/43159754/5850883f-1d3c-4090-b28d-223b9adb3d48)

I tried to remove the plugin using UnifiedPluginInstallerAgent.exe /remove Auto Photoshop Stable Diffusion Plugin, but I received the error message "Failed to remove Auto, status = -406".

Could you please help me remove the Auto.Photoshop.SD.plugin_v1.3.0 plugin from my Photoshop beta v25?

Thank you for your time and consideration.

**Comment by AbdullahAlfaraj** [comment]
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/22a77192-b5ac-4ad5-b95b-8744c5042328)

**Comment by jaceda** [comment]
> ![image](https://user-images.githubusercontent.com/7842232/261803281-22a77192-b5ac-4ad5-b95b-8744c5042328.png)

Dear sir, 
I tried to uninstall the plugin from Adobe Creative Cloud, but the uninstall area is grayed out and cannot be executed. Strangely, when I run UnifiedPluginInstallerAgent.exe /list all to check the version of Auto Photoshop Stable Diffusion Plugin, it shows 1.1.0. Now it cannot be removed by UnifiedPluginInstallerAgent.exe /remove or from Adobe Creative Cloud. I would like to ask if there are other ways to remove it. Thank you.
![sd_fail](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/43159754/44a8ac25-cd3d-4165-b911-c857b406002a)
![sd_fail2](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/43159754/fe7cc601-439d-4d44-bb1c-87534e05c714)

**Comment by jaceda** [comment]
Dear sir,
I apologize, I have found the cause. This should be a bug in Photoshop beta v25, and it may only occur in Traditional Chinese Windows 10. The attached image is the solution for Traditional Chinese Windows 10.
![sd_fail2pass](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/43159754/9ce272ec-b66c-4e77-b3b1-249a8e530460)
