### ISSUE TITLE
Controlnet Extension is missing

### ISSUE THREAD

**Issue by musostudios** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#362]
Controlnet is not working, instead I get the error "the controlnet extension is missing from Automatic1111. Please install it to use it through the plugin." I do have the controlnet extension. I see that some people  have this problem, and it can be fixed by downgrading to another version, but that does not work for me. 
I have re installed and downloaded everything and it still doesn't work. Any help please?
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/63736019/029e74dc-20e1-40ba-b41e-e2c5140e291c)

**Comment by RoyDingZF** [comment]
which one to downgrade? webui? controlnet extension? or photoshop plugin?

**Comment by zombieyang** [comment]
what is your controlnet version?

**Comment by musostudios** [comment]
Not sure how to check the controlnet version but it says its up to date in the extension tab. 
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/63736019/539656e6-a98c-4244-803e-686a8a03abfd)


> what is your controlnet version?

**Comment by Rokkonrol** [comment]
Having the same issue with ControlNet v1.1.408.

**Comment by Opeth66** [comment]
same problem. even after latest fix. automatic 1111, ControlNet v1.1.408, Adobe Photoshop Version: 25.0.0

**Comment by zombieyang** [comment]
> same problem. even after latest fix. ControlNet v1.1.408, Adobe Photoshop Version: 25.0.0

just fix in the code, I did not publish new plug-in file yet. I don't know how to publish it and can't find Abdullah... I'll learn to publish it tomorrow

**Comment by musostudios** [comment]
I followed your instructions and went into the code and replaced it with what you have and I still get the same error.

**Comment by zombieyang** [comment]
you have to run `npm run build` following the guide `First time running the plugin (local Automatic1111):` in `Method 3: The UXP method (Instruction for Developers):` in readme.

But I publish a release now:
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/releases/tag/v1.3.1

**Comment by hyde357** [comment]
I use Mac I also have the same problem

**Comment by aliksumin** [comment]
I have the same issue with Control Net in v1.4.1 of AutoPhotoshop plugin

**Comment by huameiwei-vc** [comment]
> I have the same issue with Control Net in v1.4.1 of AutoPhotoshop plugin

me too

**Comment by jlmaoju** [comment]
same here

> I have the same issue with Control Net in v1.4.1 of AutoPhotoshop plugin

**Comment by Skettalee** [comment]
Yes im on 1.4.1 right now and control net shows no extension. What extension is it that we need? I have controlnet already in auto1111
