### ISSUE TITLE
Controlnet 无法工作

### ISSUE THREAD

**Issue by haha0803** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#363]
Controlnet 无法工作，但是收到错误“Automatic1111 中缺少 controlnet 扩展。请通过插件使用它来安装它。”我确实有controlnet 扩展。我看到有些人有这个问题，可以通过降级到另一个版本来解决，但是对我不起作用。
我已经重新安装并下载了所有内容，但它仍然不起作用。有什么帮助吗？
![Snipaste_2023-09-08_01-10-01](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/55041233/76914ec6-60c2-4be2-ac90-a0eb6d498649)

**Comment by zombieyang** [comment]
duplicate with #362 
重复了
