### ISSUE TITLE
After Detailer still not working?

### ISSUE THREAD

**Issue by mikheys** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#365]
Been waiting for this update, until it looks like the after detailer in it doesn't work as well?

**Comment by zombieyang** [comment]
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/334#issuecomment-1712446841

**Comment by AbdullahAlfaraj** [comment]
fix in v1.3.2
