### ISSUE TITLE
Smart Object setting not work ( 1.3.2 )

### ISSUE THREAD

**Issue by TRGLN** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#372]
Thank you very much for the new version 1.3.2, but unfortunately the “Smart object” setting still doesn’t work
I tried to find and fix this in the code myself, but there is no response to changing values, which in my opinion may be related to this. My knowledge is not enough to fix the problem.
I reported the bug earlier https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/333#issue-1807741671
but since the new version is 1.3.2, I decided to make a separate message.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/113715629/cb68ec62-7860-49a0-84c0-5f4e4e798dc9)
Maybe there is some simple way to solve this problem? I would appreciate your help.

**Comment by AbdullahAlfaraj** [comment]
I must have missed it, thanks for the reminder.
it's now fixed in https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/pull/378/commits/2d4bc9aea35749cd7b9ee4484c81b8895d787dfb
