### ISSUE TITLE
Can't use SD extensions

### ISSUE THREAD

**Issue by Yellow-Qiu** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#381]
I have installed the SD extensions plugin, but it still shows that the plugin is not installed in Photoshop, and the Outpaint feature is not functioning properly.

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/145878944/de4ca98a-3546-4e21-b707-45960bade93d

**Comment by AbdullahAlfaraj** [comment]
You might want to grab the extension from this repo. The one you’ve got installed is a backup fork and it’s about 8 months out of date.
copy this link to your extension tab: 
`https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git`
make sure it's says: `github.com/AbdullahAlfara`

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/23697c2f-d5da-4ec6-9347-640d63794eef)

**Comment by Yellow-Qiu** [comment]
I installed the old version using the link, but it's unusable. Is there a zipped version of the plugin available?

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/145878944/8dfdb7f9-6206-4d6f-a93f-045f14e31b72

**Comment by AbdullahAlfaraj** [comment]
try to install it manually:
1) in command line go to the extension directory mine is:
`C:\Users\abdul\Desktop\automatic1111\stable-diffusion-webui\extensions`
2) delete the Auto-Photoshop folder:
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/e3cea9c2-ea86-47fd-930a-79d71d2e7a2f)
3) install the extension manually by pasting this command in the cmd window: 
`git clone https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git`

**Comment by Yellow-Qiu** [comment]
PS E:\sd-webui-aki-v4\extensions> git clone https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git

Cloning into 'Auto-Photoshop-StableDiffusion-Plugin'...
fatal: unable to access 'https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin.git/': Failed to connect to github.com port 443 after 21094 ms: Couldn't connect to server

**Comment by Yellow-Qiu** [comment]
I have downloaded it using git, but it's still the previous version
![屏幕截图 2023-09-24 100405](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/145878944/5b6b57ef-933b-4d9c-be43-99fa439290af)

**Comment by AbdullahAlfaraj** [comment]
You can still get the extension manually but then you won't be able to update it from Auto1111:
1) download the repo as zip file
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/3b5ee994-9e02-4f6f-bc21-ff0807912150)
2) extract the `Auto-Photoshop` folder to your Auto111 extension directory.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/17157d46-23d0-4f4c-996d-42b2d06228d0)

it looks like this problem is happening with all your extensions. Maybe you should get in touch with the person who’s in charge of the project you’re using to install Auto1111. my guess is that all of your extensions are likely behind the official release.

**Comment by Yellow-Qiu** [comment]
The link seems to have expired
![screenshot20230924](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/145878944/2f1df19c-402b-42f3-9fb5-32a0b72d982f)

**Comment by AbdullahAlfaraj** [comment]
which link?!

**Comment by Yellow-Qiu** [comment]
![screenshot20230924 (1)](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/145878944/1d7171bd-17d7-4514-bb2f-777996e1817a)

**Comment by Yellow-Qiu** [comment]
Thank you! The installation issue has been resolved. However, the outpaint function still seems to be problematic, and it is still unable to fill in blank areas. It only redraws what is already there (even if the layer background is made transparent, it automatically turns white).

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/145878944/34a3a040-a87c-4a7f-8134-800db0ad35b6

**Comment by Yellow-Qiu** [comment]
Thank you! The installation issue has been resolved.
