### ISSUE TITLE
auto1111 extension

### ISSUE THREAD

**Issue by zimagg** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#386]
when I launch photoshop it gives me this. What should I do to fix that? (generating images doesn't work probbably because of this)
![Zrzut ekranu 2023-09-27 210051](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/146258707/d5ad632c-f172-4dec-b632-e540f75dc63f)

**Comment by AbdullahAlfaraj** [comment]
follow this: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/380#issuecomment-1732440185

**Comment by zimagg** [comment]
But I can't find this auto1111 extension downloader or checker or something, i ran this ccx file, then added --api argument in webui user file, run webui user and webui, opened photoshop and still I can't generate anything, this error is still here

**Comment by zimagg** [comment]
omg, sorry, i'm new in github issues tab, anyway:
But I can't find this auto1111 extension downloader or checker or something, i ran this ccx file, then added --api argument in webui user file, run webui user and webui, opened photoshop and still I can't generate anything, this error is still here

**Comment by AbdullahAlfaraj** [comment]
the extension tab is part of the Auto1111 webui:
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/78db6d01-c670-47e8-8746-1c3197a61dc3)
