### ISSUE TITLE
where is the history option?

### ISSUE THREAD

**Issue by wuyue0509** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#387]
the new version v1.3.2 can't  find the history option

**Comment by AbdullahAlfaraj** [comment]
The plugin is made of three windows.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/c11a5c83-308a-400d-9a44-0a7a01843859)
1) The first window is the main plugin window.
2) is a secondary window. It’s designed for controlnet, previewing and selecting the generated images, and other features that used to require tab switching.
3) The third is a toolbar. It provides quick access to all the important buttons.

This setup is all about making your life a bit easier. No more tab switching or endless scrolling. Just a smoother, more efficient workflow.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/40fc385d-738a-422d-8857-0ff4b80a6da8)
