### ISSUE TITLE
Can't find v1.3.3, popup says I must update?!?

### ISSUE THREAD

**Issue by BigZampano** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#394]
This popup wants me to update to v1.3.3, but the latest version here is v1.3.2...?

Can anyone please show me the right direction...?

![Bildschirmfoto 2023-10-09 um 11 46 32](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/115810193/6caab601-abb0-4705-91f5-8db136ab6b81)

**Comment by AbdullahAlfaraj** [comment]
v1.3.3 should be up now.
