### ISSUE TITLE
Loading settings from image metadata puts negative prompt in main prompt window

### ISSUE THREAD

**Issue by Jonseed** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#395]
What the title says. The two prompts are combined in the same prompt window. The negative prompt should go in the negative prompt window.

**Comment by AbdullahAlfaraj** [comment]
Thank you for the report. The issue was caused by a problem in parsing. I wasn’t aware that the negative prompts I used for testing the feature had an extra leading space.

**Comment by AbdullahAlfaraj** [comment]
It's fixed now, assuming you forked the project, you can follow the steps documented here to publish your own ccx or wait till I publish an official release. 
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/pull/364
