### ISSUE TITLE
Inpainting does not generate comparable results as in A1111

### ISSUE THREAD

**Issue by madrooky** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#400]
So i have an issue to use this plugin for inpainting. 
I have an excellent inpaint model that generates very good results in a1111, often even with the first shot. It is very good to adapt to lighting and so on. I use it mainly for faces. The results are always fitting to the tone and lighting of the image and is very easy to use. Even without prompt it does an excellent job. Prompts are only necessary if i want to change some elements. I also don't use any additional plugin. It just works.

However, with this plugin the results are very different in photoshop using the lasso tool. Rectangular selection wont work at all. The first issue is denoising strength. If i use lower than around 0.8 i get a greyish blurry mess that does not resemble the input image at all. With 1.0 i kind of get a result that fits into the image but the outcome is of course very random and the color and lighting is very unsatisfying. In a1111 I normally use 0.3 - 0.7 but these values wont produce anything usable in photoshop with this plugin. 
I also use inpainting sometimes to fix some minor ugly spots, but this does not work if i have to work with full denoising strength.

It turns out that my previous practice is faster and produces better results. For a face change i mark the area and copy paste it into a1111 and paste the restult from the folder back to the image. As i don't change the edges of the image it fits perfectly. Even though this is more manual work it is faster than fiddling with the plugin and does produce so much better results without any issue.

Is there any advice what i might be overlooking? It seems to me what i do normally is actually kind of similar what the plugin does, but not to the same results.

Thanks

**Comment by AbdullahAlfaraj** [comment]
I will be able to help you better if you could provide an example and a screenshot of both the Photoshop and plugin settings. Without these, it’s difficult for me to reproduce your issue.

**Comment by madrooky** [comment]
Ok here are examples. The model used is _epicrealism_pureEvolutionV5-inpainting_.
The example picture is pre downscaled to 683x1024.
Both examples are the first shots i made with this picture, but I tested more with the PS plugin and i did not manage to produce anything better with the PS plugin.

a1111 example

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/4311794a-5cf1-44cb-a1d1-06fb6fdf1100)

PS example

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/944f2352-0417-474e-84a4-8460e1e81478)


As I said initially, when I work on high res pictures I cut out the part i want to change, paste it to a1111 and put it back in the picture afterwards. As far as I understand this is kind of similar what the plugin in PS does. But even without the context of the full picture, a1111 does a great job with shadows and tone.

**Comment by cdmusic2019** [comment]
cfg scale 7-10, step  40

**Comment by madrooky** [comment]
> cfg scale 7-10, step 40

No the model likes lower cfg scales and 30 steps with that sampler is totally fine. But I tried it nonetheless with another picture and the result was the same, even worse. The denoising is the problem and not working as expected. With default 0.7 it came out much darker and not fitting at all like in the example and 1.0 kind of worked but the lighting was off. You even see where the mask ended on the neck

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/19f0d889-c976-490b-b11e-9ed94774f0e4)

Heck I just tried to remove one of the windows in the background but the result is funny. With a blank prompt it just draws a portait of a woman, and with a prompt with "wall" in it it draws a different picture with a wall.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/f099489f-7711-4dc3-8e4b-8e6d156699ea)


Not sure what is wrong there but it seems the plugin fails to get the context of the picture. I don't even know how that works normally but with this model you can get results without any prompt, it picks up what is on the image and does something that might fit. I mean that is how reg fill from Adobe is working as well.

**Comment by madrooky** [comment]
> I will be able to help you better if you could provide an example and a screenshot of both the Photoshop and plugin settings. Without these, it’s difficult for me to reproduce your issue.

I just noticed you marked as "can't reproduce", I get it. But any Idea whats wrong? I mean how does it normally behave? Is there a different model you could recommend? Anything? I mean it would even good to get some feedback that for anyone else it is working normally. That way I would know that there must be an issue on my side.

**Comment by AbdullahAlfaraj** [comment]
@madrooky 
Hard to say exactly what’s causing your issue without a screenshot of the plugin's settings. But you see that dark shade on the girl’s face on the left? That’s usually what happens when you use ‘fill’ for inpainting instead of ‘original’.

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/637ce847-4d4c-4c1d-a2a2-b12b73ab2b2c)

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/c21ed82a-bf5a-49a1-9e01-9abbf7c09342)

**Comment by madrooky** [comment]
Oh wow, i totally missed that one... that is actually causing all the problems. It should be the default. Not sure what default is in SD as i have the webui state extension. But I can't remember to have ever changed this setting.
And also no errors any more like last time i tried. That is fine by me...^^
Thanks!
