### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by NeuroNormal** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#41]
version - v1.0.17 27715147a0b49abebf2f5a3826aff413636c3b4a

When attempting to img2img or inpaint getting this errors

> payload: {'init_image_name': 'img_31_46791.png'}
exception:fail to read an image file ./init_images/img_31_46791.png, will try again 0 of 3
exception:fail to read an image file ./init_images/img_31_46791.png, will try again 1 of 3
exception:fail to read an image file ./init_images/img_31_46791.png, will try again 2 of 3
←[32mINFO←[0m:     127.0.0.1:52058 - "←[1mPOST /getInitImage/ HTTP/1.1←[0m" ←[32m200 OK←[0m

**Comment by NeuroNormal** [comment]
dupe of #6

**Comment by AbdullahAlfaraj** [comment]
Hi @NeuroNormal, what photoshop version do you have?  you can check that in UXP while photoshop is running.
also did you follow the steps here: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/6#issuecomment-1364951594

**Comment by AbdullahAlfaraj** [comment]
hi @NeuroNormal, the last update should have fixed this problem. 
#42

**Comment by NeuroNormal** [comment]
yep, fixed, thanks!
