### ISSUE TITLE
Remote Automatic1111 without start_server.bat in directory

### ISSUE THREAD

**Issue by guoqingling** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#418]
there  is no start_server.bat but deprecate the proxy server files, how can i use remote method?
thank you !

**Comment by AbdullahAlfaraj** [comment]
You should add the url to your Auto1111 webui in here:

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/f0fce8f6-6240-46bd-9997-f3c5c5840310)

**Comment by guoqingling** [comment]
Thank you very much!
