### ISSUE TITLE
可正常生成图片，但是生成的图片并不会正常加载在图层上

### ISSUE THREAD

**Issue by godlonely** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#423]
可正常生成图片，并在界面中显示进度
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/14304355/3c88d62e-0955-448a-a323-077d92cc293b)

但是完成之后，生成的图片并不会以新图层的结果出现在PS内
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/14304355/d6d17dba-c5e7-4e5c-a515-90bfe27590f7)

在生成目录也可以找到图片
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/14304355/1958cf43-2e79-4fd5-828f-8f22ef351bfc)

使用的是PS 2024版本，不知道有没有遇到相同情况的。

**Comment by godlonely** [comment]
这个搞也行，需要去生成目录找到图片再拖回PS

**Comment by cdmusic2019** [comment]
Check this out: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/383
