### ISSUE TITLE
Real-time drawing lcm sampler

### ISSUE THREAD

**Issue by amir167** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#428]
Hi
First of all, thanks for the new version 1.4.0
is it possible to implement the real-time drawing function using lcm sampler in the comfyUI  via the Auto-Photoshop-SD plugin?

for example Photoshop has a feature that allows you to store the last stage of the layer.
To do this, rename the layer, for example, to example.png and enable the function
Generate/Image Assets

For example, how is this implemented in Krita plugins
link to the plugin
https://github.com/Acly/krita-ai-diffusion
link to the video
https://www.youtube.com/watch?v=AU8NDSBIS1U&t=6s

**Comment by AbdullahAlfaraj** [comment]
Hi Amir, 
Yes, that's a cool feature, at the moment you can use lcm sampler method in your generation to speed it up but the real time api call is missing.
I will add support to it in the next update.

**Comment by AbdullahAlfaraj** [comment]
@amir167, support for real-time generation has been added in v1.4.1 through the custom comfyui workflow panel. I will also add this feature through the main menu UI in a future update.
