### ISSUE TITLE
Workflow base and a menu observation for new version (4.0)

### ISSUE THREAD

**Issue by YarvixPA** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#429]
Hi, hope you are fine

Im happy with the new version that enable comfyUI... yesterday I start learning the basics of ComfyUI.

1) I don't know if it is due to changes but the menu to select checkpoint does not appear unless I delete the text of the checkpoint that I have selected, It open when a select but dont show the other checkpoints, same thing with lora and dont know if Textual Inversion.

2) In my case that I have automatic1111 and ComfyUI. What is the correct way to exchange when choosing which one I will use???... and if you have a base workflow that allows you to perform the different functionalities (I'm still getting to know the basic nodes), I already saw how to save a workflow to be able to use it

**Comment by drprs** [comment]
I have the same problem as well

**Comment by AbdullahAlfaraj** [comment]
@joelandresnavarro 
thanks for your feedback:
1) The issue has been resolved in version 1.4.1. Now, when you click on the searchable menus, they will immediately display a list of all available elements.
2) As for your workflow, it’s entirely up to you. You have the flexibility to run only Automatic1111, only Comfy, or use Automatic1111 for the main UI and ControlNet. Additionally, you can run your custom ComfyUI workflows to automate specific tasks that the plugin doesn’t currently support, such as a face-swapping workflow
