### ISSUE TITLE
Feedback - Problems after update from 1.33 to 1.40

### ISSUE THREAD

**Issue by madrooky** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#433]
So I updated the plugin, first that comes up is this:
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/f6a21163-7964-449a-af3a-43f900278e08)
I am not using comfy UI, so... 
I guess the comfy UI selection here is for standalone or the a1111 extension?
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/71f78cb9-eaa0-4d43-a1de-e56bab2b3806)

Next thing is breaking it for me.
I can't select a model from the drop down menu.
![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/131664307/59ac84e6-489e-49e5-9790-0cc8b19c6079)
Even after refreshing the a1111 model list where I have around 20 models ready to chose from.

I had no issues with 1.33 so I am switching back for the meantime.

**Comment by cdmusic2019** [comment]
Version 1.4 of the drop-down menu supports searching, remove it and enter keywords to select.

**Comment by AbdullahAlfaraj** [comment]
Thanks for the feedback! As cdmusic pointed out, we’ve made the large menus searchable in `v1.4.0`. Just type the model name and it’ll pop up.
Also both the searchable menu and the on start up comfyui error message have be resolve in `v1.4.1`
