### ISSUE TITLE
Values for slider width and height no displayed

### ISSUE THREAD

**Issue by DrMacabre** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#5]
hi,

changes to the values arent displayed.

![image](https://user-images.githubusercontent.com/49474452/208917504-4e7a4d3d-d838-4925-b5da-2e5503f9512e.png)

**Comment by eloidr** [comment]
have the same issue

**Comment by AbdullahAlfaraj** [comment]
this is caused by an using older photoshop version.
update to photoshop +v24
