### ISSUE TITLE
Xformers error

### ISSUE THREAD

**Issue by WickedBee** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#58]
![1111111](https://user-images.githubusercontent.com/123284290/213900255-d79eaf8f-4e58-4a90-b96f-746ae0c44458.png)
I get this when trying to run the webui-user.bat i already have installed xformers and also have installed it a second time after following this - https://www.reddit.com/r/StableDiffusion/comments/xz26lq/automatic1111_xformers_cross_attention_with_on/

**Comment by WickedBee** [comment]
update: im now getting this error - 
![12222](https://user-images.githubusercontent.com/123284290/213900656-8760f0d7-dd3c-4b5c-98e7-48b2d1a2257a.png)

**Comment by AbdullahAlfaraj** [comment]
Hi @WickedBee, 
remove the xformer form commandline argument.
in your webui-user.bat set the args to api like this.
```
set COMMANDLINE_ARGS= --api
```

**Comment by AbdullahAlfaraj** [comment]
@WickedBee if you having a hard time installing automatic1111,

then I will recommend you check this awesome repo:
https://github.com/EmpireMediaScience/A1111-Web-UI-Installer
and follow this post it shows you were to put the api argument in: 
https://discord.com/channels/1054937599392891000/1055247429244563568/1060984542208462888

**Comment by WickedBee** [comment]
![121](https://user-images.githubusercontent.com/123284290/214134563-bd9d374c-481e-4919-abbe-f07d5d65cfab.png)
i 
![1213](https://user-images.githubusercontent.com/123284290/214134569-974d6fbb-fe91-4cbb-a21f-c0652ee415ae.png)
am getting these problems with just the --api and the installer....

**Comment by AbdullahAlfaraj** [comment]
this issue has been solved. the OP forgot to add --api and save the settings. read more here: 
https://discord.com/channels/1054937599392891000/1055930551028158585/1067164943834697778
