### ISSUE TITLE
Start Server on a network?

### ISSUE THREAD

**Issue by PZAragon** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#61]
The machine running photoshop has no development environment (e.g. python). How can I start the plugin server on the same machine as SD/Automatic1111 is running and then connect the plugin on the photoshop machine to that server?

I tried setting the SD parameter pointing to the SD machine, but it still does not generate anything.

**Comment by PZAragon** [comment]
I will answer my own question, :( 

I search for all instances of "127.0.0.1:8000" and replaced them with the IP of my SD machine (e.g. http://192.168.1.99:8000).
Then edited "start_server.bat" and add "--host 192.168.1.99" to the line "%PYTHON% -m uvicorn serverMain:app --reload", so that it reads now "%PYTHON% -m uvicorn serverMain:app --host 192.168.1.99 --reload".

On the photoshop machine, open the plugin "manifest.json" on the remote machine (remember to create a network share), and continue from there. Everything appears to be working fine. 

Thanks AbdullahAlfara, for a great plugin! :)

**Comment by PZAragon** [comment]
I spoke too soon :( Generate is working fine, but both img2img and inpaint are not working (I see nothing on the SD server side for those requests). 

I have searched, but I can't find the files that deal with img2img and inpaint calls.

**Comment by AbdullahAlfaraj** [comment]
for the connecting the plugin into a remote server, you just need to change the sd_url in start_server.bat 
![image](https://user-images.githubusercontent.com/7842232/214441669-8fbf49ff-7d67-4d82-9540-5e7986d96924.png)

as for your inpainting and img2img issue, I need to see the error messages to the cmd to tell you what might have caused it.
also include you plugin version.

**Comment by PZAragon** [comment]
Hi @AbdullahAlfaraj, thanks for replying. This is not about connecting to a remote SD server, this is about connecting to aq remote plugin server.

The setup is this:
Machine A: Photoshop only
Machine B: SD and Plugin server (this is where the uvicorn server will be started)

In other words, on machine B I will run "start_server.bat" and "webui-user.bat"
Changing the SD_URL works for the SD but not for the calls to the plugin server. Because the plugin is being run by photoshop on machine B, when the plugin tries to call the uvicorn server it uses 127.0.0.1, which will fail, because 127.0.0.1 is machine B but the uvicorn server is on machine A.

I managed to fix the generate part, by the img2img and inpaint do not work. There is no error, the generation just stays stuck at 0%.

I am not sure if I was clear about the problem, please let me know if not.

**Comment by AbdullahAlfaraj** [comment]
@PZAragon thank you for being descriptive. the reason img2img mode will not work in your setup, is because the photohop plugin and the proxy server (start_server.bat) will communicate through file sharing too. 

Is there a reason why you don't want to run the uvicorn server on your pc alongside with photoshop?

**Comment by PZAragon** [comment]
Hi @AbdullahAlfaraj, I have shared the folder of Auto-Photoshop-StableDiffusion-Plugin, and photoshop is running the plugin from that network folder. That folder is also the same "physical" folder where the proxy server (start_server.bat) is being run.

The reason for this setup is that the photoshop machine is a dedicated machine for photoshop (and after effects, etc) and it has no development environment. So no conda, pip, python, etc.

**Comment by makingpippop** [comment]
@PZAragon did you manage to make it work? I think this kind of setup is pretty interesting since, like you said, it requires no development environment on the machine running photoshop.

**Comment by AbdullahAlfaraj** [comment]
@makingpippop This is an old post was made before we streamed line the whole setup.
Try this:
- install the plugin using method 1 or 2. 
- change the sd url from the settings menu to connect to remote instance

![image](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/assets/7842232/b02212bb-2cc9-426a-89bc-e398c837cf75)
