### ISSUE TITLE
Plugin does not show "Init Inpaint Mask" button

### ISSUE THREAD

**Issue by nytafar** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#69]
Running 1.1.0, I follow the instructions for outpaint, but the "Init Inpaint Mask" button does not show up, "Set init image" only shows in the Viewer tab, but I believe this is not the same as the button that is supposed to show in the main tab.

Running photoshop 14.1 and automatic1111 webui pulled today on macos ventura 13.1

**Comment by Arigocan** [comment]
I have the same issue :)

**Comment by navarisun** [comment]
me too the same issue

**Comment by AbdullahAlfaraj** [comment]
we removed those buttons in v1.1.0 to streamline the workflow. 
for txt2img, img2img, and outpaint mode you just make a selection and then click generate.

for inpaint mode you make a new layer or use the one plugin create for you when you click the inpaint mode radio option.
then make a selection and paint white inside the mask layer then hit generate.

**Comment by dhrgusdlrns** [comment]
Okay, I got it now. But I think you should explain it with more detail. 
Make a 512 x 512 rectangle and paint white on the part you want to edit.
Then click it. As he said

But be careful, If you don't use inpaint model or small area for reference, you'll get bad result.
If you want to add the an arm, you should make a 512x512 layer which includes other parts of body, like belly or shoulder whatever. 
If you make just 128 X 512 layer which only includes the space for arm, you will get a bad result.

**Comment by navarisun** [comment]
@AbdullahAlfaraj yes iafter comenting, i noticed these empty layers created on inpaint and img2img. And i figured out how it works.

Thx for imazing plugin
