### ISSUE TITLE
How do i use it with Stable diffusion Horde?

### ISSUE THREAD

**Issue by MahdeenSky** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#73]
How do i use this with stable diffusion horde? What do i set the API url to?

**Comment by taircn** [comment]
You have to install Stable Horde extension
![image](https://user-images.githubusercontent.com/55391500/215349603-0f87ecef-4da7-4d5a-8fd2-e74f61fb3f5f.png)

**Comment by MahdeenSky** [comment]
So you have to install the model to use it? Doesn't this webUI come with the model as well?

**Comment by AbdullahAlfaraj** [comment]
@MahdeenSky don't know if Automatic1111 still requires you install at least one model. 
but after you get the webui webpage running, you don't need to install any models to use the hordes.
you could also run auto1111 in cpu mode.

**Comment by MahdeenSky** [comment]
alright thanks
