### ISSUE TITLE
Clicking refresh does not doing anything

### ISSUE THREAD

**Issue by zaramal** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#81]
The plugin is looking great! I am excited to start using it. I already have SD 1.5 so I followed the youtube tutorial and everything installed fine. The cats load and I added the URL of SD but when I click refresh 'A' remains red. P is green. Not sure what the issue is. I even removed / from the URL.

**Comment by AbdullahAlfaraj** [comment]
@zaramal did you check this comment?
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/43#issuecomment-1369720783 
if the letter A is red it means the proxy server couldn't connect to automatic1111.
Double check that you have --api and make sure you have the endpoints exposed in http://127.0.0.1:7860/docs

as for the trailing "/" bug, it's not an issue anymore.

**Comment by zaramal** [comment]
I have --api "set COMMANDLINE_ARGS=--vae-path "models\VAE\vae-ft-mse-840000-ema-pruned.pt"--api --xformers"
