### ISSUE TITLE
Is there an easy installer?

### ISSUE THREAD

**Issue by anders0821** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#84]

**Comment by AbdullahAlfaraj** [comment]
@anders0821 Did you check the youtube installation tutorial?
If you have automatic1111 install it should take few minutes to get the whole setup up and running.

Also, we do have a one click installer/ .ccx file currently in beta testing stage.

**Comment by anders0821** [comment]
An one-click installer will be friendly to artists.

**Comment by AbdullahAlfaraj** [comment]
@anders0821 by the way the one click installer has been released.
