### ISSUE TITLE
Problems with img2img, inpaint and updating

### ISSUE THREAD

**Issue by giuliastro** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#89]
Hello,
I am having an hard time doing img2img and inpaint. Videos and instructions don't seem to be correct, there is no way on my side to set the mask, the "set mask" button under "viewer" doesn't seem to work while "set init image" doesn't work every time as expected. Also, it's not clear what needs to be the mask and what the image, since the results, when I rarely happen to make it work, are unpredictable.

The plugin installs nicely through the CCX but updating with a pull seems to break it and make it disappear from the list of Photoshop plugins. What is the correct way to update it?

Thank you in advance and keep the good work.

**Comment by giuliastro** [comment]
Reopening, as I keep experiencing these problems. Thank you.

**Comment by AbdullahAlfaraj** [comment]
@giuliastro check the [Wiki](https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/wiki) it has a lot of tutorials, most of the features are documented there.

if you are using the uxp method, it will auto update every time you run the "start_server.bat"
for the one click installer/ccx you will have to download the newest .ccx file and run it that's all.
I recommend you use the one click installer and update frequently. the latest version we've released is v1.1.7

**Comment by giuliastro** [comment]
Thank you so much Abdullah, please keep the great work you are doing.
