### ISSUE TITLE
Settings and inpaint question

### ISSUE THREAD

**Issue by drawtide** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#95]
hi, I have two questions.

The first question is, the SD url of settings will be restored to "127.0.0.1:7860" every time I reopen it, I want to keep a specific URL, so I don't need to re-enter it every time I reopen it, what should I do?

The second problem is that inpaint mode, every time I finish calculating the picture, after clicking the check or cross button, the white mask layer I drew will be deleted. Can I keep my layers at this stage? I would like to use it to create a mask to remove the background so that I can quickly remove the background from a new layer created with AI.

English is not my native language, so please forgive me if it is not clear. Thank you for making such a great tool.

**Comment by AbdullahAlfaraj** [comment]
@drawtide To answer your first question, we're working on a save settings feature, we'll probably release in the upcoming update.

As for the second problem, that was the default behavior in previous releases, you had to delete the mask manually, which gave you a lot of freedom to do as you mentioned, extract the silhouette of a subject. 
If there is demand for it, I'll make a settings' option to keep the mask.

**Comment by cheestor** [comment]
Hello, thank you for your hard work,

Same for me, I would love to be able to apply the mask on the inpainting result or keep it to apply it later, instead of having a "rectangle" result. It would make things a lot easier.

**Comment by drawtide** [comment]
> @drawtide To answer your first question, we're working on a save settings feature, we'll probably release in the upcoming update.
> 
> As for the second problem, that was the default behavior in previous releases, you had to delete the mask manually, which gave you a lot of freedom to do as you mentioned, extract the silhouette of a subject. If there is demand for it, I'll make a settings' option to keep the mask.

Thank you for your reply. I'm looking forward to the next version. Regarding the second question about keeping the mask, it would be very convenient for me if I could have this feature.

**Comment by AbdullahAlfaraj** [comment]
We've implemented a way for you to keep the mask in "v1.2.0". If you paint on the temporary layer 'Mask - Paint White to Mask - temporary' the mask will be deleted.
And if you paint the mask on any other layer, the mask will be kept.

@drawtide as for your first issue, you can save your sd url from the settings tab as of "v1.2.0" too

**Comment by drawtide** [comment]
Thank you very much, this is great, I have noticed your updates and have used the new controlnet feature, really great!
