### ISSUE TITLE
hi res not working

### ISSUE THREAD

**Issue by twocomet** [AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin#98]
The hi res option does not work in txt2img.
Using photoshop 2023.
webui latest version

**Comment by AbdullahAlfaraj** [comment]
@twocomet I think automatic1111 has recently flipped the way the width and hi_res_width sliders work, 
I'll look into it, to be sure.

**Comment by twocomet** [comment]
> @twocomet automatic1111이 최근에 너비와 hi_res_width 슬라이더가 작동하는 방식을 뒤집었다고 생각합니다.

Should I modify the ccx?

**Comment by twocomet** [comment]
I solved it.
Changing >512 to >=512 fixed it.
